package com.kayak.rpt.zz.manage;

import com.kayak.rpt.zz.manage.model.AssetDebtRegisterInfo;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class ManageInfoUtil {

    public static List<AssetDebtRegisterInfo> initDebtRegister(List<List<String>> datas, Map<String, Object> params) {
        List<AssetDebtRegisterInfo> infos = new ArrayList<>();
        for (int i = 0; i < datas.size(); i++) {
            AssetDebtRegisterInfo adi = new AssetDebtRegisterInfo();
            try {
                List<String> rowList = datas.get(i);
                adi.setAssetCode(StringUtils.isEmpty(rowList.get(0)) ? null : rowList.get(0));
                adi.setBankCode(StringUtils.isEmpty(rowList.get(1)) ? null : rowList.get(1));
                adi.setAssDebtType(StringUtils.isEmpty(rowList.get(2)) ? null : rowList.get(2).split(" ")[0]);
                adi.setTradeVenue(StringUtils.isEmpty(rowList.get(3)) ? null : rowList.get(3).split(" ")[0]);
                adi.setCur(StringUtils.isEmpty(rowList.get(4)) ? null : rowList.get(4).split(" ")[0]);
                adi.setBbDepositBank(StringUtils.isEmpty(rowList.get(5)) ? null : rowList.get(5));
                adi.setBbAccountNo(StringUtils.isEmpty(rowList.get(6)) ? null : rowList.get(6));
                adi.setBbDepositAmt(StringUtils.isEmpty(rowList.get(7)) ? null : rowList.get(7));
                adi.setBbValueDate(StringUtils.isEmpty(rowList.get(8)) ? null : rowList.get(8).replace("-", ""));
                adi.setBbMaturityDate(StringUtils.isEmpty(rowList.get(9)) ? null : rowList.get(9).replace("-", ""));
                adi.setBbAnnualRate(StringUtils.isEmpty(rowList.get(10)) ? null : rowList.get(10));
                adi.setBbInterestBasis(StringUtils.isEmpty(rowList.get(11)) ? null : rowList.get(11).split(" ")[0]);
                adi.setBbDepositType(StringUtils.isEmpty(rowList.get(12)) ? null : rowList.get(12).split(" ")[0]);
                adi.setBbStructDepositType(StringUtils.isEmpty(rowList.get(13)) ? null : rowList.get(13).split(" ")[0]);
                adi.setBbStructDeposit(StringUtils.isEmpty(rowList.get(14)) ? null : rowList.get(14));
                adi.setCcIdentCode(StringUtils.isEmpty(rowList.get(15)) ? null : rowList.get(15));
                adi.setCcName(StringUtils.isEmpty(rowList.get(16)) ? null : rowList.get(16));
                adi.setCcSpecificBondType(StringUtils.isEmpty(rowList.get(17)) ? null : rowList.get(17));
                adi.setCcIssModeBond(StringUtils.isEmpty(rowList.get(18)) ? null : rowList.get(18));
                adi.setCcIssRatePart(StringUtils.isEmpty(rowList.get(19)) ? null : rowList.get(19));
                adi.setCcInstituteTypeScale(StringUtils.isEmpty(rowList.get(20)) ? null : rowList.get(20).split(" ")[0]);
                adi.setCcInstituteTypeTech(StringUtils.isEmpty(rowList.get(21)) ? null : rowList.get(21).split(" ")[0]);
                adi.setCcInstituteTypeEconomic(StringUtils.isEmpty(rowList.get(22)) ? null : rowList.get(22).split(" ")[0]);
                adi.setCcIndustryIssuer(StringUtils.isEmpty(rowList.get(23)) ? null : rowList.get(23));
                adi.setCcRegistDeposit(StringUtils.isEmpty(rowList.get(24)) ? null : rowList.get(24).split(" ")[0]);
                adi.setCcDetailsRegistDeposit(StringUtils.isEmpty(rowList.get(25)) ? null : rowList.get(25));
                adi.setDdValueDate(StringUtils.isEmpty(rowList.get(26)) ? null : rowList.get(26).replace("-", ""));
                adi.setDdMaturityDate(StringUtils.isEmpty(rowList.get(27)) ? null : rowList.get(27).replace("-", ""));
                adi.setDdCounterparty(StringUtils.isEmpty(rowList.get(28)) ? null : rowList.get(28));
                adi.setDdCounterpartyType(StringUtils.isEmpty(rowList.get(29)) ? null : rowList.get(29).split(" ")[0]);
                adi.setDdAnnalInterestRate(StringUtils.isEmpty(rowList.get(30)) ? null : rowList.get(30));
                adi.setDdInterestBasis(StringUtils.isEmpty(rowList.get(31)) ? null : rowList.get(31).split(" ")[0]);
                adi.setDdCollateralType(StringUtils.isEmpty(rowList.get(32)) ? null : rowList.get(32).split(" ")[0]);
                adi.setDdCollateralValue(StringUtils.isEmpty(rowList.get(33)) ? null : rowList.get(33));
                adi.setEeOwnershipType(StringUtils.isEmpty(rowList.get(34)) ? null : rowList.get(34).split(" ")[0]);
                adi.setEeBuyback(StringUtils.isEmpty(rowList.get(35)) ? null : rowList.get(35).split(" ")[0]);
                adi.setEeName(StringUtils.isEmpty(rowList.get(36)) ? null : rowList.get(36));
                adi.setEeAssetCode(StringUtils.isEmpty(rowList.get(37)) ? null : rowList.get(37));
                adi.setEeAmt(StringUtils.isEmpty(rowList.get(38)) ? null : rowList.get(38));
                adi.setEeUnitParValue(StringUtils.isEmpty(rowList.get(39)) ? null : rowList.get(39));
                adi.setEeValueDate(StringUtils.isEmpty(rowList.get(40)) ? null : rowList.get(40).replace("-", ""));
                adi.setEeMaturityDate(StringUtils.isEmpty(rowList.get(41)) ? null : rowList.get(41).replace("-", ""));
                adi.setEeStatutoryMaturityDate(StringUtils.isEmpty(rowList.get(42)) ? null : rowList.get(42).replace("-", ""));
                adi.setEeExpectedReturn(StringUtils.isEmpty(rowList.get(43)) ? null : rowList.get(43).split(" ")[0]);
                adi.setEeProjectAnnaulReturn(StringUtils.isEmpty(rowList.get(44)) ? null : Double.valueOf(rowList.get(44)));
                adi.setEeCouponType(StringUtils.isEmpty(rowList.get(45)) ? null : rowList.get(45).split(" ")[0]);
                adi.setEeRegualrInterestPay(StringUtils.isEmpty(rowList.get(46)) ? null : rowList.get(46).split(" ")[0]);
                adi.setEeInterestPayFrequency(StringUtils.isEmpty(rowList.get(47)) ? null : rowList.get(47));
                adi.setEeCouponAllocationType(StringUtils.isEmpty(rowList.get(48)) ? null : rowList.get(48).split(" ")[0]);
                adi.setEeDetailPrincInterest(StringUtils.isEmpty(rowList.get(49)) ? null : rowList.get(49));
                adi.setEeInterestBasis(StringUtils.isEmpty(rowList.get(50)) ? null : rowList.get(50).split(" ")[0]);
                adi.setEeBenchRateType(StringUtils.isEmpty(rowList.get(51)) ? null : rowList.get(51).split(" ")[0]);
                adi.setEeFloatFactor(StringUtils.isEmpty(rowList.get(52)) ? null : rowList.get(52).split(" ")[0]);
                adi.setEeFloatRate(StringUtils.isEmpty(rowList.get(53)) ? null : Double.valueOf(rowList.get(53)));
                adi.setEeYieldSpreadBp(StringUtils.isEmpty(rowList.get(54)) ? null : Double.valueOf(rowList.get(54)));
                adi.setEeStructGrade(StringUtils.isEmpty(rowList.get(55)) ? null : rowList.get(55).split(" ")[0]);
                adi.setEePrincPaymentType(StringUtils.isEmpty(rowList.get(56)) ? null : rowList.get(56).split(" ")[0]);
                adi.setEeInstallRepayType(StringUtils.isEmpty(rowList.get(57)) ? null : rowList.get(57).split(" ")[0]);
                adi.setEeBaseAssetType(StringUtils.isEmpty(rowList.get(58)) ? null : rowList.get(58));
                adi.setEePercentExcInAllot(StringUtils.isEmpty(rowList.get(59)) ? null : Double.valueOf(rowList.get(59)));
                adi.setEeDebtor(StringUtils.isEmpty(rowList.get(60)) ? null : rowList.get(60));
                adi.setEeDeptorRate(StringUtils.isEmpty(rowList.get(61)) ? null : rowList.get(61).split(" ")[0]);
                adi.setEeRateAgencyIss(StringUtils.isEmpty(rowList.get(62)) ? null : rowList.get(62));
                adi.setEeDebtorTypeScale(StringUtils.isEmpty(rowList.get(63)) ? null : rowList.get(63).split(" ")[0]);
                adi.setEeDebtorTypeTech(StringUtils.isEmpty(rowList.get(64)) ? null : rowList.get(64).split(" ")[0]);
                adi.setEeDebtorTypeEconomic(StringUtils.isEmpty(rowList.get(65)) ? null : rowList.get(65).split(" ")[0]);
                adi.setEeProject(StringUtils.isEmpty(rowList.get(66)) ? null : rowList.get(66));
                adi.setEeIndustryDebtor(StringUtils.isEmpty(rowList.get(67)) ? null : rowList.get(67).split(" ")[0]);
                adi.setEeMonitorIndusType(StringUtils.isEmpty(rowList.get(68)) ? null : rowList.get(68).split(" ")[0]);
                adi.setEeMonitorIndustryType(StringUtils.isEmpty(rowList.get(69)) ? null : rowList.get(69).split(" ")[0]);
                adi.setEeDetailsMonitoryType(StringUtils.isEmpty(rowList.get(70)) ? null : rowList.get(70));
                adi.setEeGuaranteeMethod(StringUtils.isEmpty(rowList.get(71)) ? null : rowList.get(71).split(" ")[0]);
                adi.setEePledgeType(StringUtils.isEmpty(rowList.get(72)) ? null : rowList.get(72).split(" ")[0]);
                adi.setEePledgeValue(StringUtils.isEmpty(rowList.get(73)) ? null : rowList.get(73));
                adi.setEeGuaranteeType(StringUtils.isEmpty(rowList.get(74)) ? null : rowList.get(74).split(" ")[0]);
                adi.setEeGuarantorType(StringUtils.isEmpty(rowList.get(75)) ? null : rowList.get(75).split(" ")[0]);
                adi.setEeDetailGuaranteeStatus(StringUtils.isEmpty(rowList.get(76)) ? null : rowList.get(76));
                adi.setEeDebtorRate(StringUtils.isEmpty(rowList.get(77)) ? null : rowList.get(77).split(" ")[0]);
                adi.setEeInterAssetRate(StringUtils.isEmpty(rowList.get(78)) ? null : rowList.get(78).split(" ")[0]);
                adi.setEeOutAssetRate(StringUtils.isEmpty(rowList.get(79)) ? null : rowList.get(79).split(" ")[0]);
                adi.setEeOptionType(StringUtils.isEmpty(rowList.get(80)) ? null : rowList.get(80).split(" ")[0]);
                adi.setEeExerciseDateType(StringUtils.isEmpty(rowList.get(81)) ? null : rowList.get(81).split(" ")[0]);
                adi.setEeFixedExerciseDate(StringUtils.isEmpty(rowList.get(82)) ? null : rowList.get(82).replace("-", ""));
                adi.setEeFirstExerciseDate(StringUtils.isEmpty(rowList.get(83)) ? null : rowList.get(83).replace("-", ""));
                adi.setEeExercisePeriod(StringUtils.isEmpty(rowList.get(84)) ? null : rowList.get(84));
                adi.setEeExercisePrice(StringUtils.isEmpty(rowList.get(85)) ? null : rowList.get(85));
                adi.setEePerpetualType(StringUtils.isEmpty(rowList.get(86)) ? null : rowList.get(86).split(" ")[0]);
                adi.setEeDeferreInterestType(StringUtils.isEmpty(rowList.get(87)) ? null : rowList.get(87).split(" ")[0]);
                adi.setEeInterestDeferred(StringUtils.isEmpty(rowList.get(88)) ? null : rowList.get(88).split(" ")[0]);
                adi.setEeFirstRepriceDate(StringUtils.isEmpty(rowList.get(89)) ? null : rowList.get(89).replace("-", ""));
                adi.setEeRepricePeriod(StringUtils.isEmpty(rowList.get(90)) ? null : rowList.get(90));
                adi.setEePartialRedemption(StringUtils.isEmpty(rowList.get(91)) ? null : rowList.get(91).split(" ")[0]);
                adi.setEePartialRedemptionRate(StringUtils.isEmpty(rowList.get(92)) ? null : Double.valueOf(rowList.get(92)));
                adi.setEeOptionRight(StringUtils.isEmpty(rowList.get(93)) ? null : rowList.get(93));
                adi.setEeDetailsExerciseTerm(StringUtils.isEmpty(rowList.get(94)) ? null : rowList.get(94));
                String eRegionDebtor = rowList.get(95);
                adi.setEeRegionDebtor(StringUtils.isEmpty(eRegionDebtor) ? null : eRegionDebtor.split(" ")[0]);
                adi.setEeOrganizationCode(StringUtils.isEmpty(rowList.get(96)) ? null : rowList.get(96));
                adi.setEeEnhanceInstituteCode(StringUtils.isEmpty(rowList.get(97)) ? null : rowList.get(97));
                adi.setEeEnhanceInstituteName(StringUtils.isEmpty(rowList.get(98)) ? null : rowList.get(98));
                adi.setEeTotalFeeRate(StringUtils.isEmpty(rowList.get(99)) ? null : Double.valueOf(rowList.get(99)));
                adi.setEeIndustryProject(StringUtils.isEmpty(rowList.get(100)) ? null : rowList.get(100).split(" ")[0]);
                adi.setFfOwnership(StringUtils.isEmpty(rowList.get(101)) ? null : rowList.get(101).split(" ")[0]);
                adi.setFfBuyback(StringUtils.isEmpty(rowList.get(102)) ? null : rowList.get(102).split(" ")[0]);
                adi.setFfType(StringUtils.isEmpty(rowList.get(103)) ? null : rowList.get(103).split(" ")[0]);
                adi.setFfStandarBill(StringUtils.isEmpty(rowList.get(104)) ? null : rowList.get(104));
                adi.setFfNoteCode(StringUtils.isEmpty(rowList.get(105)) ? null : rowList.get(105));
                adi.setFfQuantity(StringUtils.isEmpty(rowList.get(106)) ? null : rowList.get(106));
                adi.setFfAggregateAmt(StringUtils.isEmpty(rowList.get(107)) ? null : rowList.get(107));
                adi.setFfWeightRemainDay(StringUtils.isEmpty(rowList.get(108)) ? null : rowList.get(108));
                adi.setFfMaxRemainDay(StringUtils.isEmpty(rowList.get(109)) ? null : rowList.get(109));
                adi.setFfMinRemainFay(StringUtils.isEmpty(rowList.get(110)) ? null : rowList.get(110));
                adi.setFfValueDate(StringUtils.isEmpty(rowList.get(111)) ? null : rowList.get(111).replace("-", ""));
                adi.setFfMaturityDate(StringUtils.isEmpty(rowList.get(112)) ? null : rowList.get(112).replace("-", ""));
                adi.setFfIndustry(StringUtils.isEmpty(rowList.get(113)) ? null : rowList.get(113).split(" ")[0]);
                adi.setFfDiscountRate(StringUtils.isEmpty(rowList.get(114)) ? null : rowList.get(114));
                adi.setGgStockCode(StringUtils.isEmpty(rowList.get(115)) ? null : rowList.get(115));
                adi.setGgName(StringUtils.isEmpty(rowList.get(116)) ? null : rowList.get(116));
                adi.setGgStockType(StringUtils.isEmpty(rowList.get(117)) ? null : rowList.get(117).split(" ")[0]);
                adi.setGgIndustry(StringUtils.isEmpty(rowList.get(118)) ? null : rowList.get(118).split(" ")[0]);
                adi.setGgInvestStage(StringUtils.isEmpty(rowList.get(119)) ? null : rowList.get(119).split(" ")[0]);
                adi.setGgEquityOutDate(StringUtils.isEmpty(rowList.get(120)) ? null : rowList.get(120));
                adi.setGgEnterTypeScale(StringUtils.isEmpty(rowList.get(121)) ? null : rowList.get(121).split(" ")[0]);
                adi.setGgEnterTypeTech(StringUtils.isEmpty(rowList.get(122)) ? null : rowList.get(122).split(" ")[0]);
                adi.setGgEnterTypeEconomic(StringUtils.isEmpty(rowList.get(123)) ? null : rowList.get(123).split(" ")[0]);
                adi.setGgPledgedFinace(StringUtils.isEmpty(rowList.get(124)) ? null : rowList.get(124).split(" ")[0]);
                adi.setGgDebtEquitySwap(StringUtils.isEmpty(rowList.get(125)) ? null : rowList.get(125).split(" ")[0]);
                adi.setHhName(StringUtils.isEmpty(rowList.get(126)) ? null : rowList.get(126));
                adi.setHhNominalPrincipal(StringUtils.isEmpty(rowList.get(127)) ? null : rowList.get(127));
                adi.setHhUnderAssetType(StringUtils.isEmpty(rowList.get(128)) ? null : rowList.get(128).split(" ")[0]);
                adi.setHhHoldObjective(StringUtils.isEmpty(rowList.get(129)) ? null : rowList.get(129).split(" ")[0]);
                adi.setIiCountyRegion(StringUtils.isEmpty(rowList.get(130)) ? null : rowList.get(130).split(" ")[0]);
                adi.setIiBondName(StringUtils.isEmpty(rowList.get(131)) ? null : rowList.get(131));
                adi.setIiBondIdentCode(StringUtils.isEmpty(rowList.get(132)) ? null : rowList.get(132));
                adi.setIiIssuer(StringUtils.isEmpty(rowList.get(133)) ? null : rowList.get(133));
                adi.setIiIndustryIssuer(StringUtils.isEmpty(rowList.get(134)) ? null : rowList.get(134).split(" ")[0]);
                adi.setIiValueDate(StringUtils.isEmpty(rowList.get(135)) ? null : rowList.get(135).replace("-", ""));
                adi.setIiMaturityDate(StringUtils.isEmpty(rowList.get(136)) ? null : rowList.get(136).replace("-", ""));
                adi.setIiTermMaturity(StringUtils.isEmpty(rowList.get(137)) ? null : rowList.get(137));
                adi.setIiIssuerRateBond(StringUtils.isEmpty(rowList.get(138)) ? null : rowList.get(138));
                adi.setIiBondRate(StringUtils.isEmpty(rowList.get(139)) ? null : rowList.get(139));
                adi.setIiCoupRate(StringUtils.isEmpty(rowList.get(140)) ? null : rowList.get(140));
                adi.setIiInterestPayQuency(StringUtils.isEmpty(rowList.get(141)) ? null : rowList.get(141));
                adi.setIiDetailsAssureStatus(StringUtils.isEmpty(rowList.get(142)) ? null : rowList.get(142));
                adi.setIiDetailsSpecialTerms(StringUtils.isEmpty(rowList.get(143)) ? null : rowList.get(143));
                adi.setJjCountry(StringUtils.isEmpty(rowList.get(144)) ? null : rowList.get(144).split(" ")[0]);
                adi.setJjValueDate(StringUtils.isEmpty(rowList.get(145)) ? null : rowList.get(145).replace("-", ""));
                adi.setJjMaturityDate(StringUtils.isEmpty(rowList.get(146)) ? null : rowList.get(146).replace("-", ""));
                adi.setJjCounterparty(StringUtils.isEmpty(rowList.get(147)) ? null : rowList.get(147));
                adi.setJjInterestRate(StringUtils.isEmpty(rowList.get(148)) ? null : rowList.get(148));
                adi.setJjInterestBasis(StringUtils.isEmpty(rowList.get(149)) ? null : rowList.get(149).split(" ")[0]);
                adi.setKkCountry(StringUtils.isEmpty(rowList.get(150)) ? null : rowList.get(150).split(" ")[0]);
                adi.setKkIdentCode(StringUtils.isEmpty(rowList.get(151)) ? null : rowList.get(151));
                adi.setKkName(StringUtils.isEmpty(rowList.get(152)) ? null : rowList.get(152));
                adi.setKkIssuer(StringUtils.isEmpty(rowList.get(153)) ? null : rowList.get(153));
                adi.setKkIndustry(StringUtils.isEmpty(rowList.get(154)) ? null : rowList.get(154).split(" ")[0]);
                adi.setLlCountry(StringUtils.isEmpty(rowList.get(155)) ? null : rowList.get(155).split(" ")[0]);
                adi.setLlContractName(StringUtils.isEmpty(rowList.get(156)) ? null : rowList.get(156));
                adi.setLlValueDate(StringUtils.isEmpty(rowList.get(157)) ? null : rowList.get(157).replace("-", ""));
                adi.setLlMaturityDate(StringUtils.isEmpty(rowList.get(158)) ? null : rowList.get(158).replace("-", ""));
                adi.setLlCouponRate(StringUtils.isEmpty(rowList.get(159)) ? null : rowList.get(159));
                adi.setLlInterestFrequency(StringUtils.isEmpty(rowList.get(160)) ? null : rowList.get(160));
                adi.setLlPercentFix(StringUtils.isEmpty(rowList.get(161)) ? null : rowList.get(161));
                adi.setLlPercentDerivate(StringUtils.isEmpty(rowList.get(162)) ? null : rowList.get(162));
                adi.setLlDerivateInvetType(StringUtils.isEmpty(rowList.get(163)) ? null : rowList.get(163));
                adi.setLlUnderAsset(StringUtils.isEmpty(rowList.get(164)) ? null : rowList.get(164));
                adi.setLlDetailsProceeds(StringUtils.isEmpty(rowList.get(165)) ? null : rowList.get(165));
                adi.setLlDetailsOption(StringUtils.isEmpty(rowList.get(166)) ? null : rowList.get(166));
                adi.setLlMaxNoteReturn(StringUtils.isEmpty(rowList.get(167)) ? null : rowList.get(167));
                adi.setLlMinNoteReturn(StringUtils.isEmpty(rowList.get(168)) ? null : rowList.get(168));
                adi.setLlStrikeUnderAsset(StringUtils.isEmpty(rowList.get(169)) ? null : rowList.get(169));
                adi.setLlUnderRgPrice(StringUtils.isEmpty(rowList.get(170)) ? null : rowList.get(170));
                adi.setLlTransCosts(StringUtils.isEmpty(rowList.get(171)) ? null : rowList.get(171));
                adi.setMmManagePlanName(StringUtils.isEmpty(rowList.get(172)) ? null : rowList.get(172));
                adi.setMmManageProduct(StringUtils.isEmpty(rowList.get(173)) ? null : rowList.get(173).split(" ")[0]);
                adi.setMmProductCode(StringUtils.isEmpty(rowList.get(174)) ? null : rowList.get(174));
                adi.setMmIssuedAssetCompany(StringUtils.isEmpty(rowList.get(175)) ? null : rowList.get(175).split(" ")[0]);
                adi.setMmPlanIssuerCode(StringUtils.isEmpty(rowList.get(176)) ? null : rowList.get(176));
                adi.setMmAssetPlanRgCode(StringUtils.isEmpty(rowList.get(177)) ? null : rowList.get(177));
                adi.setMmManager(StringUtils.isEmpty(rowList.get(178)) ? null : rowList.get(178));
                adi.setMmCustodian(StringUtils.isEmpty(rowList.get(179)) ? null : rowList.get(179));
                adi.setMmAmt(StringUtils.isEmpty(rowList.get(180)) ? null : rowList.get(180));
                adi.setMmActualDirect(StringUtils.isEmpty(rowList.get(181)) ? null : rowList.get(181).split(" ")[0]);
                adi.setMmDetailsInvest(StringUtils.isEmpty(rowList.get(182)) ? null : rowList.get(182));
                adi.setMmIndustryInvest(StringUtils.isEmpty(rowList.get(183)) ? null : rowList.get(183));
                adi.setMmPlanStartDate(StringUtils.isEmpty(rowList.get(184)) ? null : rowList.get(184).replace("-", ""));
                adi.setMmPlanMaturityDate(StringUtils.isEmpty(rowList.get(185)) ? null : rowList.get(185).replace("-", ""));
                adi.setMmPlanType(StringUtils.isEmpty(rowList.get(186)) ? null : rowList.get(186).split(" ")[0]);
                adi.setMmExpectedReturn(StringUtils.isEmpty(rowList.get(187)) ? null : rowList.get(187).split(" ")[0]);
                adi.setMmMaxExpectedReturn(StringUtils.isEmpty(rowList.get(188)) ? null : Double.valueOf(rowList.get(188)));
                adi.setMmMinExpectedReturn(StringUtils.isEmpty(rowList.get(189)) ? null : Double.valueOf(rowList.get(189)));
                adi.setMmInvestStructure(StringUtils.isEmpty(rowList.get(190)) ? null : rowList.get(190).split(" ")[0]);
                adi.setMmManagerType(StringUtils.isEmpty(rowList.get(191)) ? null : rowList.get(191));
                adi.setMmManagerFeeRate(StringUtils.isEmpty(rowList.get(192)) ? null : Double.valueOf(rowList.get(192)));
                adi.setMmCustodianFeeRate(StringUtils.isEmpty(rowList.get(193)) ? null : Double.valueOf(rowList.get(193)));
                adi.setMmTransCostRate(StringUtils.isEmpty(rowList.get(194)) ? null : Double.valueOf(rowList.get(194)));
                adi.setMmInterFeeRate(StringUtils.isEmpty(rowList.get(195)) ? null : Double.valueOf(rowList.get(195)));
                adi.setMmOtherExpenseRate(StringUtils.isEmpty(rowList.get(196)) ? null : Double.valueOf(rowList.get(196)));
                adi.setNnCountry(StringUtils.isEmpty(rowList.get(197)) ? null : rowList.get(197).split(" ")[0]);
                adi.setNnName(StringUtils.isEmpty(rowList.get(198)) ? null : rowList.get(198));
                adi.setNnTermDays(StringUtils.isEmpty(rowList.get(199)) ? null : rowList.get(199));
                adi.setNnAssetValue(StringUtils.isEmpty(rowList.get(200)) ? null : rowList.get(200));
                adi.setNnAssetReturn(StringUtils.isEmpty(rowList.get(201)) ? null : rowList.get(201));
                adi.setSsName(StringUtils.isEmpty(rowList.get(202)) ? null : rowList.get(202));
                adi.setSsAssetType(StringUtils.isEmpty(rowList.get(203)) ? null : rowList.get(203).split(" ")[0]);
                adi.setSsDetailsAssetType(StringUtils.isEmpty(rowList.get(204)) ? null : rowList.get(204));
                adi.setSsAmt(StringUtils.isEmpty(rowList.get(205)) ? null : rowList.get(205));
                adi.setSsValueDate(StringUtils.isEmpty(rowList.get(206)) ? null : rowList.get(206).replace("-", ""));
                adi.setSsMaturityDate(StringUtils.isEmpty(rowList.get(207)) ? null : rowList.get(207).replace("-", ""));
                adi.setSsCountry(StringUtils.isEmpty(rowList.get(208)) ? null : rowList.get(208).split(" ")[0]);
                adi.setSsExpectedReturn(StringUtils.isEmpty(rowList.get(209)) ? null : rowList.get(209).split(" ")[0]);
                adi.setSsAnnualReturn(StringUtils.isEmpty(rowList.get(210)) ? null : Double.valueOf(rowList.get(210)));
                adi.setSsInterestFrequency(StringUtils.isEmpty(rowList.get(211)) ? null : rowList.get(211));
                adi.setSsDebtor(StringUtils.isEmpty(rowList.get(212)) ? null : rowList.get(212));
                adi.setSsOrganCode(StringUtils.isEmpty(rowList.get(213)) ? null : rowList.get(213));
                adi.setSsRateAgencyIss(StringUtils.isEmpty(rowList.get(214)) ? null : rowList.get(214));
                adi.setSsDebtorTypeScale(StringUtils.isEmpty(rowList.get(215)) ? null : rowList.get(215).split(" ")[0]);
                adi.setSsDebtorTypeTech(StringUtils.isEmpty(rowList.get(216)) ? null : rowList.get(216).split(" ")[0]);
                adi.setSsDebtorTypeEconomic(StringUtils.isEmpty(rowList.get(217)) ? null : rowList.get(217).split(" ")[0]);
                adi.setSsProject(StringUtils.isEmpty(rowList.get(218)) ? null : rowList.get(218));
                adi.setSsIndustryDebtor(StringUtils.isEmpty(rowList.get(219)) ? null : rowList.get(219).split(" ")[0]);
                adi.setSsIndustryProject(StringUtils.isEmpty(rowList.get(220)) ? null : rowList.get(220).split(" ")[0]);
                adi.setSsMonitoryIndustry(StringUtils.isEmpty(rowList.get(221)) ? null : rowList.get(221).split(" ")[0]);
                adi.setSsMonitoryIndustryType(StringUtils.isEmpty(rowList.get(222)) ? null : rowList.get(222).split(" ")[0]);
                adi.setSsDetailsMonitoryType(StringUtils.isEmpty(rowList.get(223)) ? null : rowList.get(223));
                adi.setSsInternalAssetRate(StringUtils.isEmpty(rowList.get(224)) ? null : rowList.get(224).split(" ")[0]);
                adi.setSsGuaranteeMethod(StringUtils.isEmpty(rowList.get(225)) ? null : rowList.get(225).split(" ")[0]);
                adi.setSsPledgeType(StringUtils.isEmpty(rowList.get(226)) ? null : rowList.get(226).split(" ")[0]);
                adi.setSsPledgeValue(StringUtils.isEmpty(rowList.get(227)) ? null : rowList.get(227));
                adi.setSsGuaranteeType(StringUtils.isEmpty(rowList.get(228)) ? null : rowList.get(228).split(" ")[0]);
                adi.setSsGuarantorType(StringUtils.isEmpty(rowList.get(229)) ? null : rowList.get(229).split(" ")[0]);
                adi.setSsDetailsGuarantee(StringUtils.isEmpty(rowList.get(230)) ? null : rowList.get(230));
                adi.setSsDebtEquitySwap(StringUtils.isEmpty(rowList.get(231)) ? null : rowList.get(231).split(" ")[0]);
                adi.setOoCountry(StringUtils.isEmpty(rowList.get(232)) ? null : rowList.get(232).split(" ")[0]);
                adi.setOoName(StringUtils.isEmpty(rowList.get(233)) ? null : rowList.get(233).split(" ")[0]);
                adi.setOoValueDate(StringUtils.isEmpty(rowList.get(234)) ? null : rowList.get(234).replace("-", ""));
                adi.setOoMaturityDate(StringUtils.isEmpty(rowList.get(235)) ? null : rowList.get(235).replace("-", ""));
                adi.setOoAssetValue(StringUtils.isEmpty(rowList.get(236)) ? null : rowList.get(236));
                adi.setOoAssetReturn(StringUtils.isEmpty(rowList.get(237)) ? null : rowList.get(237).split(" ")[0]);
                adi.setPpFundCode(StringUtils.isEmpty(rowList.get(238)) ? null : rowList.get(238));
                adi.setPpFundName(StringUtils.isEmpty(rowList.get(239)) ? null : rowList.get(239));
                adi.setPpIndustry(StringUtils.isEmpty(rowList.get(240)) ? null : rowList.get(240).split(" ")[0]);
                adi.setPpRegistAgency(StringUtils.isEmpty(rowList.get(241)) ? null : rowList.get(241).split(" ")[0]);
                adi.setPpFixedIncome(StringUtils.isEmpty(rowList.get(242)) ? null : rowList.get(242).split(" ")[0]);
                adi.setPpGovernInvestFund(StringUtils.isEmpty(rowList.get(243)) ? null : rowList.get(243).split(" ")[0]);
                adi.setPpDirectGovernFund(StringUtils.isEmpty(rowList.get(244)) ? null : rowList.get(244).split(" ")[0]);
                adi.setPpIssuedAssetCompany(StringUtils.isEmpty(rowList.get(245)) ? null : rowList.get(245).split(" ")[0]);
                adi.setPpTaName(StringUtils.isEmpty(rowList.get(246)) ? null : rowList.get(246));
                adi.setPpManagerFundName(StringUtils.isEmpty(rowList.get(247)) ? null : rowList.get(247));
                adi.setPpCustodianFundName(StringUtils.isEmpty(rowList.get(248)) ? null : rowList.get(248));
                adi.setPpInvestStage(StringUtils.isEmpty(rowList.get(249)) ? null : rowList.get(249).split(" ")[0]);
                adi.setPpEnterTypeScale(StringUtils.isEmpty(rowList.get(250)) ? null : rowList.get(250).split(" ")[0]);
                adi.setPpEnterTypeTech(StringUtils.isEmpty(rowList.get(251)) ? null : rowList.get(251).split(" ")[0]);
                adi.setPpEnterTypeEconomic(StringUtils.isEmpty(rowList.get(252)) ? null : rowList.get(252).split(" ")[0]);
                adi.setPpInvestAssets(StringUtils.isEmpty(rowList.get(253)) ? null : rowList.get(253));
                adi.setQqOutAgreementName(StringUtils.isEmpty(rowList.get(254)) ? null : rowList.get(254));
                adi.setQqOutAgreementCode(StringUtils.isEmpty(rowList.get(255)) ? null : rowList.get(255));
                adi.setQqTrustee(StringUtils.isEmpty(rowList.get(256)) ? null : rowList.get(256));
                adi.setQqActualManager(StringUtils.isEmpty(rowList.get(257)) ? null : rowList.get(257));
                adi.setQqCustodian(StringUtils.isEmpty(rowList.get(258)) ? null : rowList.get(258));
                adi.setQqOutAmt(StringUtils.isEmpty(rowList.get(259)) ? null : rowList.get(259));
                adi.setQqActualDirection(StringUtils.isEmpty(rowList.get(260)) ? null : rowList.get(260).split(" ")[0]);
                adi.setQqDetailsInvest(StringUtils.isEmpty(rowList.get(261)) ? null : rowList.get(261));
                adi.setQqIndustryInvest(StringUtils.isEmpty(rowList.get(262)) ? null : rowList.get(262).split(" ")[0]);
                adi.setQqValueDate(StringUtils.isEmpty(rowList.get(263)) ? null : rowList.get(263).replace("-", ""));
                adi.setQqMaturityDate(StringUtils.isEmpty(rowList.get(264)) ? null : rowList.get(264).replace("-", ""));
                adi.setQqOutType(StringUtils.isEmpty(rowList.get(265)) ? null : rowList.get(265).split(" ")[0]);
                adi.setQqExpectedReturn(StringUtils.isEmpty(rowList.get(266)) ? null : rowList.get(266).split(" ")[0]);
                adi.setQqMaxExpectedReturn(StringUtils.isEmpty(rowList.get(267)) ? null : rowList.get(267));
                adi.setQqMinExpectedReturn(StringUtils.isEmpty(rowList.get(268)) ? null : rowList.get(268));
                adi.setQqManagerFeeRate(StringUtils.isEmpty(rowList.get(269)) ? null : rowList.get(269));
                adi.setQqCustodianFeeRate(StringUtils.isEmpty(rowList.get(270)) ? null : rowList.get(270));
                adi.setQqTransCostRate(StringUtils.isEmpty(rowList.get(271)) ? null : rowList.get(271));
                adi.setQqInterFeeRate(StringUtils.isEmpty(rowList.get(272)) ? null : rowList.get(272));
                adi.setQqOtherExpensesRate(StringUtils.isEmpty(rowList.get(273)) ? null : rowList.get(273));
                adi.setRrCountry(StringUtils.isEmpty(rowList.get(274)) ? null : rowList.get(274).split(" ")[0]);
                adi.setRrName(StringUtils.isEmpty(rowList.get(275)) ? null : rowList.get(275));
                adi.setRrTermMaturity(StringUtils.isEmpty(rowList.get(276)) ? null : rowList.get(276));
                adi.setRrLiabilityAmt(StringUtils.isEmpty(rowList.get(277)) ? null : rowList.get(277));
                adi.setRrInterestRate(StringUtils.isEmpty(rowList.get(278)) ? null : rowList.get(278));
                adi.setRrCashBorrow(StringUtils.isEmpty(rowList.get(279)) ? null : rowList.get(279).split(" ")[0]);
                adi.setDetails(StringUtils.isEmpty(rowList.get(280)) ? null : rowList.get(280));
                adi.setTheoryReportStartDate(String.valueOf(params.get("beginDate")));
                infos.add(adi);
            } catch (IndexOutOfBoundsException ex) {
                infos.add(adi);
                continue;
            }
        }
        return infos;
    }
}
