<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pms_server</groupId>
		<artifactId>k-cloud-service-starters</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>k-cloud-service-starter-micro-server</artifactId>
	<version>1.0.0</version>
	<name>k-cloud-service-starter-micro-server</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<dependency>
			<groupId>pms_server</groupId>
			<artifactId>k-cloud-action</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>pms_server</groupId>
			<artifactId>k-cloud-cache</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
