<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>pms_server</groupId>
		<artifactId>k-cloud-service</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>k-cloud-schedule</artifactId>
	<version>1.0.0</version>
	<name>k-cloud-schedule</name>
	<url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<dependency>
			<groupId>pms_server</groupId>
			<artifactId>k-cloud-service-starter-micro-server</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-all</artifactId>
			<version>5.5.6</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>pms_server</groupId>-->
<!--			<artifactId>k-cloud-discovery-nacos</artifactId>-->
<!--			<version>1.0.0</version>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.quartz-scheduler</groupId>
			<artifactId>quartz</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
            <version>1.9.7</version>
        </dependency>
		 <dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.11.2</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/src/main/resources/lib/log4j-api-2.11.2.jar</systemPath>
		</dependency>
    </dependencies>

	<build>
		<finalName>scheduleApp</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>1.5.8.RELEASE</version>
				<configuration>
					<includeSystemScope>true</includeSystemScope>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>