package com.kayak.rpt.zz.operate.service;

import cn.hutool.core.bean.BeanUtil;
import com.kayak.core.system.SysUtil;
import com.kayak.core.util.Tools;
import com.kayak.rpt.zz.manage.model.InvestorSubHoldInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.kayak.aspect.annotations.API;
import com.kayak.aspect.annotations.APIAuth;
import com.kayak.aspect.annotations.APIDefine;
import com.kayak.core.sql.SqlParam;
import com.kayak.core.sql.SqlResult;
import com.kayak.rpt.zz.operate.dao.InvestorSubHoldMarkDao;
import com.kayak.rpt.zz.operate.model.InvestorSubHoldMark;

@Service
@APIDefine(desc = "投资者持有信息(子产品)操作记录服务", model = InvestorSubHoldMark.class)
public class InvestorSubHoldMarkService {

	@Autowired
	private InvestorSubHoldMarkDao investorSubHoldMarkDao;

	@API(desc = "查询投资者持有信息(子产品)信息", auth = APIAuth.YES)
	public SqlResult<InvestorSubHoldMark> findInvestorSubHoldMarks(SqlParam<InvestorSubHoldMark> params) throws Exception {
		params.setMakeSql(true);
		return investorSubHoldMarkDao.findInvestorSubHoldMarks(params);
	}

	@API(desc = "添加投资者持有信息(子产品)", params = "id,prod_code,prod_name,prod_full_name,cb_reg_code,pb_reg_code,invest_asset_type,prod_oper_mod,subscr_type,mng_mth,prod_term,prod_brnd,prod_tms,fund_cur,paym_prcp_cur,paym_income_cur,subscr_start_date,subscr_end_date,early_termin_mark,customer_redem_mark,prod_cred_enhanc_mark,prod_cred_enhanc_instit_type,prod_cred_enhanc_mtd,dms_custody_instit_code,ovs_custody_instit_nation,dms_custody_instit_name,ovs_custody_instit_name,prod_value_date,prod_matur_date,prod_matur_date_origin,prod_matur_date_cb,prod_matur_date_pb,stru_prod_mark,cash_mng_mark,inter_open_peri,other_regu_open_peri,prod_stat,prod_return_type,prod_compli_type,fina_insti_exclu_mark,invest_region,speci_country_region,wealth_mng_serv_mod,prod_asset_alloc_mtd,prod_mng_mod,actual_mng_name,price_mtd,perfm_benchm_rate,min_hold_prei_mark,min_hold_peri,min_hold_peri_redem_mark,prod_sale_region,invest_thresh,sale_commis_rate,custody_fee_rate,subscr_start_date_earliest,subscr_end_date_latest,plan_fund_amount,invest_risk_prefer,prod_risk_rate,prod_speci_proper,invest_mng_fee_rate,cooper_mod,cooperator,invest_princ_due_date,invest_income_due_date,invest_asset_type_ratio,prod_approv_name,prod_approv_id,prod_design_name,prod_design_id,invest_mng_name,invest_mng_id,filing_conta_name,filing_conta_work_phone,filing_conta_mobile_phone,filing_conta_mail,prior_ratio,perfm_benchm_upper_limit,perfm_benchm_lower_limit,perfm_benchm_detail,open_mod,regu_open_peri,irregu_open_peri_detail,first_open_peri_start_date,holid_open_mark,aver_open_frequ,open_peri_busin_type,open_peri_busin_type_detail,fund_custody_acco_no,fund_custody_acco_name,msg_type,prod_change_date,custody_org_mng_duty,iconme_rgt_trans_prod_mark,cross_border_wealth_mng_platf,trust_prod_type,base_info_open_mark,change_reason,prod_renewal_mark,liquidate_mark", auth = APIAuth.NO)
	public int addInvestorSubHoldMark(InvestorSubHoldInfo investorSubHoldInfo, String operType) throws Exception {
		InvestorSubHoldMark investorHold = BeanUtil.copyProperties(investorSubHoldInfo, InvestorSubHoldMark.class);
		investorHold.setOpType(operType);
		investorHold.setOpUser(Tools.obj2Str(SysUtil.getSysUserParamValue("sys_user_username")));
		return investorSubHoldMarkDao.addInvestorSubHoldMark(investorHold).getEffect();
	}

	@API(desc = "修改投资者持有信息(子产品)", params = "id,prod_code,prod_name,prod_full_name,cb_reg_code,pb_reg_code,invest_asset_type,prod_oper_mod,subscr_type,mng_mth,prod_term,prod_brnd,prod_tms,fund_cur,paym_prcp_cur,paym_income_cur,subscr_start_date,subscr_end_date,early_termin_mark,customer_redem_mark,prod_cred_enhanc_mark,prod_cred_enhanc_instit_type,prod_cred_enhanc_mtd,dms_custody_instit_code,ovs_custody_instit_nation,dms_custody_instit_name,ovs_custody_instit_name,prod_value_date,prod_matur_date,prod_matur_date_origin,prod_matur_date_cb,prod_matur_date_pb,stru_prod_mark,cash_mng_mark,inter_open_peri,other_regu_open_peri,prod_stat,prod_return_type,prod_compli_type,fina_insti_exclu_mark,invest_region,speci_country_region,wealth_mng_serv_mod,prod_asset_alloc_mtd,prod_mng_mod,actual_mng_name,price_mtd,perfm_benchm_rate,min_hold_prei_mark,min_hold_peri,min_hold_peri_redem_mark,prod_sale_region,invest_thresh,sale_commis_rate,custody_fee_rate,subscr_start_date_earliest,subscr_end_date_latest,plan_fund_amount,invest_risk_prefer,prod_risk_rate,prod_speci_proper,invest_mng_fee_rate,cooper_mod,cooperator,invest_princ_due_date,invest_income_due_date,invest_asset_type_ratio,prod_approv_name,prod_approv_id,prod_design_name,prod_design_id,invest_mng_name,invest_mng_id,filing_conta_name,filing_conta_work_phone,filing_conta_mobile_phone,filing_conta_mail,prior_ratio,perfm_benchm_upper_limit,perfm_benchm_lower_limit,perfm_benchm_detail,open_mod,regu_open_peri,irregu_open_peri_detail,first_open_peri_start_date,holid_open_mark,aver_open_frequ,open_peri_busin_type,open_peri_busin_type_detail,fund_custody_acco_no,fund_custody_acco_name,msg_type,prod_change_date,custody_org_mng_duty,iconme_rgt_trans_prod_mark,cross_border_wealth_mng_platf,trust_prod_type,base_info_open_mark,change_reason,prod_renewal_mark,liquidate_mark", auth = APIAuth.NO)
	public int updateInvestorSubHoldMark(SqlParam<InvestorSubHoldMark> params) throws Exception {
		return investorSubHoldMarkDao.updateInvestorSubHoldMark(params).getEffect();
	}

	@API(desc = "删除投资者持有信息(子产品)", params = "id,prod_code,prod_name,prod_full_name,cb_reg_code,pb_reg_code,invest_asset_type,prod_oper_mod,subscr_type,mng_mth,prod_term,prod_brnd,prod_tms,fund_cur,paym_prcp_cur,paym_income_cur,subscr_start_date,subscr_end_date,early_termin_mark,customer_redem_mark,prod_cred_enhanc_mark,prod_cred_enhanc_instit_type,prod_cred_enhanc_mtd,dms_custody_instit_code,ovs_custody_instit_nation,dms_custody_instit_name,ovs_custody_instit_name,prod_value_date,prod_matur_date,prod_matur_date_origin,prod_matur_date_cb,prod_matur_date_pb,stru_prod_mark,cash_mng_mark,inter_open_peri,other_regu_open_peri,prod_stat,prod_return_type,prod_compli_type,fina_insti_exclu_mark,invest_region,speci_country_region,wealth_mng_serv_mod,prod_asset_alloc_mtd,prod_mng_mod,actual_mng_name,price_mtd,perfm_benchm_rate,min_hold_prei_mark,min_hold_peri,min_hold_peri_redem_mark,prod_sale_region,invest_thresh,sale_commis_rate,custody_fee_rate,subscr_start_date_earliest,subscr_end_date_latest,plan_fund_amount,invest_risk_prefer,prod_risk_rate,prod_speci_proper,invest_mng_fee_rate,cooper_mod,cooperator,invest_princ_due_date,invest_income_due_date,invest_asset_type_ratio,prod_approv_name,prod_approv_id,prod_design_name,prod_design_id,invest_mng_name,invest_mng_id,filing_conta_name,filing_conta_work_phone,filing_conta_mobile_phone,filing_conta_mail,prior_ratio,perfm_benchm_upper_limit,perfm_benchm_lower_limit,perfm_benchm_detail,open_mod,regu_open_peri,irregu_open_peri_detail,first_open_peri_start_date,holid_open_mark,aver_open_frequ,open_peri_busin_type,open_peri_busin_type_detail,fund_custody_acco_no,fund_custody_acco_name,msg_type,prod_change_date,custody_org_mng_duty,iconme_rgt_trans_prod_mark,cross_border_wealth_mng_platf,trust_prod_type,base_info_open_mark,change_reason,prod_renewal_mark,liquidate_mark", auth = APIAuth.NO)
	public int deleteInvestorSubHoldMark(SqlParam<InvestorSubHoldMark> params) throws Exception {
		return investorSubHoldMarkDao.deleteInvestorSubHoldMark(params).getEffect();
	}
}
