package com.kayak.pms.netValue.service;

import com.kayak.aspect.annotations.API;
import com.kayak.aspect.annotations.APIAuth;
import com.kayak.aspect.annotations.APIDefine;
import com.kayak.aspect.annotations.APIOperation;
import com.kayak.core.sql.SqlParam;
import com.kayak.core.sql.SqlResult;
import com.kayak.core.util.DateUtil;
import com.kayak.pms.disclosureControl.dao.DisclosureWorkdayDao;
import com.kayak.pms.disclosureControl.dao.ScheduleProdRuleDao;
import com.kayak.pms.disclosureControl.model.DisclosureWorkday;
import com.kayak.pms.disclosureControl.model.ScheduleProdRule;
import com.kayak.pms.netValue.dao.T8ProdNetvalDaysDao;
import com.kayak.pms.netValue.model.T8ProdNetvalDays;
import com.kayak.pms.netValue.util.NetValUtil;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
@APIDefine(desc = "产品净值披露日期服务", model = T8ProdNetvalDays.class)
public class T8ProdNetvalDaysService {

	@Autowired
	private T8ProdNetvalDaysDao t8ProdNetvalDaysDao;
	@Autowired
	private ScheduleProdRuleDao scheduleProdRuleDao;
	@Autowired
	private DisclosureWorkdayDao disclosureWorkdayDao;

	@API(desc = "查询产品净值披露日期信息", auth = APIAuth.YES)
	public SqlResult<T8ProdNetvalDays> findT8ProdNetvalDayss(SqlParam<T8ProdNetvalDays> params) throws Exception {
		params.setMakeSql(true);
		return t8ProdNetvalDaysDao.findT8ProdNetvalDayss(params);
	}

	@API(desc = "添加产品净值披露日期", auth = APIAuth.NO)
	public int addT8ProdNetvalDays(SqlParam<T8ProdNetvalDays> params) throws Exception {
		return t8ProdNetvalDaysDao.addT8ProdNetvalDays(params).getEffect();
	}

	@API(desc = "修改产品净值披露日期", auth = APIAuth.NO)
	public int updateT8ProdNetvalDays(SqlParam<T8ProdNetvalDays> params) throws Exception {
		return t8ProdNetvalDaysDao.updateT8ProdNetvalDays(params).getEffect();
	}

	@API(desc = "删除产品净值披露日期", auth = APIAuth.NO)
	public int deleteT8ProdNetvalDays(SqlParam<T8ProdNetvalDays> params) throws Exception {
		return t8ProdNetvalDaysDao.deleteT8ProdNetvalDays(params).getEffect();
	}


	/**
	 * 功能：自动跑批调用 每月28号跑 生成基准日期落在下个月的净值披露日期数据
	 * 作者：rennannan
	 * 日期：20210621
	 *
	 * @param params
	 * @throws Exception
	 */
	@API(desc = "自动跑批生成产品净值披露日期", auth = APIAuth.NO, operation = APIOperation.INSTER)
	public void autoGenerateDays(SqlParam<T8ProdNetvalDays> params) throws Exception {
		//获取当前日期
		String nowDate = DateUtil.getNowDate();

		//获取下月日期
		String nextMonthDate = DateUtil.calculation(nowDate, "yyyyMMdd", 1, Calendar.MONTH);
		//获取下月第一天与最后一天
		String nextMonthFirstDay = DateUtil.getFirstDayDateOfMonth(nextMonthDate);
		String nextMonthEndDate = DateUtil.getLastDayOfMonth(nextMonthDate);
		String month = nextMonthDate.substring(0, 6);
		List<T8ProdNetvalDays> netValueDays = getNetvalDaysList(nextMonthFirstDay, nextMonthEndDate, month);
		if (netValueDays.size() > 0) {
			addAndDelNetvalList(netValueDays, month);
		}
	}

	/**
	 * 功能：查询日期区间的产品净值披露日期
	 * 作者：rennannan
	 * 日期：20210621
	 *
	 * @param
	 * @param
	 * @return
	 * @throws Exception
	 */
	public List<T8ProdNetvalDays> getNetvalDaysList(String monthFirstDate, String monthEndDate, String month) throws Exception {
		//查询t8_disclosure_prod_rule表中信披类型为9（净值公告）且发起方式为时间规则发起的数据
		ScheduleProdRule prodRule = new ScheduleProdRule();
		prodRule.setDisclosureType("9");//信披类型  净值公告
		prodRule.setStartRule("2");//发起方式  时间规则发起
		List<ScheduleProdRule> prodRuleList = scheduleProdRuleDao.findProdRulesByType(prodRule);
		List<T8ProdNetvalDays> t8ProdNetvalDaysList = new ArrayList<>();

		//下个月的开始日期与结束日期
		String nextMonthDate = DateUtil.calculation(monthFirstDate, "yyyyMMdd", 1, Calendar.MONTH);//获取下个月日期
		String nextMonthStartDate = DateUtil.getFirstDayDateOfMonth(nextMonthDate);//获取下月最后一天
		String nextMonthEndDate = DateUtil.getLastDayOfMonth(nextMonthDate);

		//查询本月银行间工作日
		List<DisclosureWorkday> bankWorkDayList = getDealWorkDays("001", monthFirstDate, monthEndDate);

		//查询下月银行间第一个工作日
		String nextMonthBankDay = "";
		List<DisclosureWorkday> nextBankDayList = getDealWorkDays("001", nextMonthStartDate, nextMonthEndDate);
		if (nextBankDayList.size() > 0) {
			nextMonthBankDay = nextBankDayList.get(0).getWorkday();
		}

		//查询本月期间交易所工作日

		List<DisclosureWorkday> dealWorkDayList = getDealWorkDays("002", monthFirstDate, monthEndDate);

		//查询传入日期下个月期间交易所工作日
		List<DisclosureWorkday> dealTwoMonthWorkDayList = getDealWorkDays("002", nextMonthStartDate, nextMonthEndDate);

		for (ScheduleProdRule scheProdRule : prodRuleList) {
			t8ProdNetvalDaysList.addAll(getProdNetValList(scheProdRule, monthFirstDate, monthEndDate, dealWorkDayList, month, dealTwoMonthWorkDayList, bankWorkDayList, nextMonthBankDay));
		}
		return t8ProdNetvalDaysList;
	}

	/**
	 * 功能：根据工作方案编号和日期区间查询工作日
	 * 作者：rennannan
	 * 日期：20210623
	 *
	 * @return
	 */
	public List<DisclosureWorkday> getDealWorkDays(String pgmno, String startDate, String endDate) throws Exception {
		Map<String, String> dealParam = new HashMap<>();
		dealParam.put("pgmno", "002");
		dealParam.put("startDate", startDate);
		dealParam.put("endDate", endDate);
		List<DisclosureWorkday> dealWorkDayList = disclosureWorkdayDao.findWorkDayByPgmNo(dealParam);
		return dealWorkDayList;
	}

	/**
	 * 功能：查询单个产品净值披露规则的对应的披露日期
	 *
	 * @param scheProdRule            信披规则
	 * @param monthFirstDay           开始日期
	 * @param monthEndDate            结束日期
	 * @param dealWorkDayList         交易所工作日
	 * @param month                   所属月份
	 * @param dealTwoMonthWorkDayList 下个月交易所工作日
	 * @param bankWorkDayList         银行间工作日
	 * @param nextMonthBankDay        下个月银行间第一个工作日
	 * @return
	 * @throws Exception
	 */
	public List<T8ProdNetvalDays> getProdNetValList(ScheduleProdRule scheProdRule,
													String monthFirstDay, String monthEndDate,
													List<DisclosureWorkday> dealWorkDayList,
													String month, List<DisclosureWorkday> dealTwoMonthWorkDayList,
													List<DisclosureWorkday> bankWorkDayList,
													String nextMonthBankDay) throws Exception {
		List<T8ProdNetvalDays> t8ProdNetValDaysList = new ArrayList<>();

		String prodInfoId = scheProdRule.getT8ProdInfoId();//产品id
		String prodCode = scheProdRule.getProdCode();//产品代码
		String netValueDateStr = scheProdRule.getNetValueDate();//基准日期 多个，以“,”分隔
		String netValueDateRule = scheProdRule.getNetValueDateRule();//披露日期规则
		String netValueDates[] = netValueDateStr.split(",");//基准日期数组

		//净值日期需要加的天数   加上以后才能得出披露日期
		int addDays = NetValUtil.getAddDays(netValueDateRule);

		//查询本月所有工作日  查询表为sys_workday_set
		Map<String, String> workdayParam = new HashMap<>();
		workdayParam.put("t8ProdInfoId", prodInfoId);
		workdayParam.put("startDate", monthFirstDay);
		workdayParam.put("endDate", monthEndDate);
		//根据产品id查询对应工作日方案中的工作日
		List<DisclosureWorkday> netDays = this.disclosureWorkdayDao.findWorkDay(workdayParam);

		Set<String> set = new HashSet<String>();
		for (int i = 0; i < netValueDates.length; i++) {//基准日期
			String netValueDate = netValueDates[i];//单个基准日期
			String netValDate = ""; //查询得出的净值日期（基准日期） yyyymmdd

			switch (netValueDate) {
				case "01":  //银行间工作日（工作日披露工作日及相邻节假日）  取sys_workday_set中pgmno为001的
					for (int j = 0; j < bankWorkDayList.size(); j++) {
						//工作日
						netValDate = bankWorkDayList.get(j).getWorkday();
						if (!set.contains(netValDate)) {//不存在才插入
							t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
							set.add(netValDate);
						}
						String nextDate = "";
						if (j < (bankWorkDayList.size() - 1)) {//不是最后一个工作日
							//下一个工作日
							nextDate = bankWorkDayList.get(j + 1).getWorkday();

						} else {//最后一个工作日  判断与下个月的银行间第一个工作日相差天数是否大于1，如果大于1说明是节假日前的工作日
							if (StringUtils.isNotEmpty(nextMonthBankDay)) {//下个月的工作日存在
								nextDate = nextMonthBankDay;
							} else {//不存在则取下个月第一日
								nextDate = DateUtil.getNextMonthFirstDay(monthFirstDay);
							}

						}
						//判断两个工作日之间相差的天数
						int diffDays = DateUtil.getdifferentDays(netValDate, nextDate);
						//如果大于1天说明 第一个工作日是节假日前的工作日需要将后面的节假日也在这一天披露
						if (diffDays > 1) {
							//循环取节假日的次数为相差天数减1次    如20210516和20210518相差天数为2，说明20210517的需要在20210516披露，那么需要循环的次数为1
							String tempDate = netValDate;
							for (int k = 1; k < diffDays; k++) {
								//得出的日期tempDate为净值日期  工作日为披露日期
								tempDate = DateUtil.add(tempDate, "yyyyMMdd", 1);
								t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, tempDate, addDays, month, netValueDate, netValDate));
								set.add(netValDate);
							}
						}

					}
					break;
				case "02": //每个交易所工作日 直接取sys_workday_set中pgmno为002的
					for (DisclosureWorkday wd : dealWorkDayList) {
						netValDate = wd.getWorkday();
						if (!set.contains(netValDate)) {//不存在才插入
							t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
							set.add(netValDate);
						}

					}
					break;
				case "03": //交易所节假日前最后一个工作日 sys_workday_set表中取pgmno为002的
					for (int j = 0; j < dealWorkDayList.size(); j++) {
						if (j < dealWorkDayList.size() - 1) {
							//如果两个工作日之间相差天数大于1，则证明第一个日期为节假日前最后一个工作日
							if (DateUtil.getdifferentDays(dealWorkDayList.get(j).getWorkday(), dealWorkDayList.get(j + 1).getWorkday()) > 1) {
								netValDate = dealWorkDayList.get(j).getWorkday();
								if (!set.contains(netValDate)) {//不存在才插入
									t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
									set.add(netValDate);
								}
							}
						} else {
							//判断最后一个工作日是否为节假日前的工作日
							String lastWorkDay = dealWorkDayList.get(j).getWorkday();
							String nextWorkDay = DateUtil.add(lastWorkDay, "yyyyMMdd", 1);
							//判断最后一个工作日的下一日是否存在，如果存在，说明不是节假日前的工作日，如果不存在，说明是节假日前的工作日
							boolean isHolidayBefore = true;//是否为节假日前的工作日 默认是
							for (DisclosureWorkday dwd : dealTwoMonthWorkDayList) {
								if (dwd.getWorkday().equals(nextWorkDay)) {
									isHolidayBefore = false;//非节假日前的工作日
									break;
								}
							}
							if (isHolidayBefore) {
								if (!set.contains(lastWorkDay)) {//不存在才插入
									t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, lastWorkDay, addDays, month, netValueDate, ""));
									set.add(lastWorkDay);
								}
							}
						}
					}
					break;
				case "04": //月末最后一个工作日 sys_workday_set表中取，日期区间本月的最后一日
					netValDate = netDays.get(netDays.size() - 1).getWorkday();
					if (!set.contains(netValDate)) {//不存在才插入
						t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
						set.add(netValDate);
					}
					break;
				case "05": //开放日 从t8_prod_days表中取值
					//查询产品的开放日
					Map<String, String> openParam = new HashMap<>();
					openParam.put("prodId", prodInfoId);
					openParam.put("startDate", monthFirstDay);
					openParam.put("endDate", monthEndDate);
					List<DisclosureWorkday> openDaysList = disclosureWorkdayDao.findProdOpenDays(openParam);
					for (DisclosureWorkday wd : openDaysList) {
						netValDate = wd.getWorkday();
						if (!set.contains(netValDate)) {//不存在才插入
							t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
							set.add(netValDate);
						}
					}
					break;
				case "06": //封闭投资日   从t8_prod_schedule表中取值  根据产品代码和日期区间查询
					Map<String, String> closeParam = new HashMap<>();
					closeParam.put("prodCode", prodCode);
					closeParam.put("startDate", monthFirstDay);
					closeParam.put("endDate", monthEndDate);
					List<DisclosureWorkday> closeDaysList = disclosureWorkdayDao.findCloseDays(closeParam);
					for (DisclosureWorkday cd : closeDaysList) {
						//封闭开始日期
						netValDate = cd.getCloseStartDate();
						if (!set.contains(netValDate)) {//不存在才插入
							t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
							set.add(netValDate);
						}

						//封闭结束日期
						netValDate = cd.getCloseEndDate();
						if (!set.contains(netValDate)) {//不存在才插入
							t8ProdNetValDaysList.add(setNetvalDaysProp(prodInfoId, netValDate, addDays, month, netValueDate, ""));
							set.add(netValDate);
						}
					}
					break;
			}
		}
		return t8ProdNetValDaysList;
	}

	/**
	 * 功能：给产品净值披露日期实体赋值
	 * 作者：rennannan
	 * 日期：20210622
	 * 参数： prodInfoId 产品id  netValueDate基准日期 yyyymmdd  addDays净值日期需要加的天数 month所属月份 type基准日期类型
	 *
	 * @return
	 */
	public T8ProdNetvalDays setNetvalDaysProp(String prodInfoId, String netValueDate, int addDays, String month, String type, String disDate) throws Exception {
		T8ProdNetvalDays days = new T8ProdNetvalDays();
		days.setNetvalDateType(type);//基准日期类型
		days.setMonth(month);//所属月份
		days.setType("0");//0代表批量插入
		if (StringUtils.isEmpty(disDate)) {//如果传入的披露日期不为空，则取传入的披露日期，否则需要计算
			disDate = getDisclosureDateByDays(netValueDate, addDays, prodInfoId);//披露日期
		}
		days.setNetvalDate(netValueDate);//净值日期
		days.setDisclosureDate(disDate);//披露日期
		days.setStatus("0");//状态  默认0 未确认
		days.setT8ProdInfoId(prodInfoId);//产品id
		return days;
	}

	/**
	 * 功能:根据基准日期和需要加的天数、产品id得到最后披露日期
	 * 作者：rennannan
	 * 日期：20210622
	 *
	 * @return
	 */
	public String getDisclosureDateByDays(String netValDate, int addDays, String prodInfoId) throws Exception {
		String disclosureDate = "";
		if (addDays == 0) {//T+0  如果设置的披露规则为T+0 那么披露日期就是净值日期（基准日期）
			disclosureDate = netValDate;
		} else {//否则，去工作日方案表中查询净值日期T+N后的工作日
			disclosureDate = getDisclosureDate(prodInfoId, addDays, netValDate);
		}
		return disclosureDate;
	}

	/**
	 * 功能：根据产品id、基准日期、需要加的天数查询披露日期
	 * 作者：rennannan
	 * 日期：20210622
	 *
	 * @return
	 */
	public String getDisclosureDate(String prodId, int days, String workday) throws Exception {
		String disclosureDate = "";
		Map<String, String> param = new HashMap<String, String>();
		param.put("prodId", prodId);
		param.put("days", Integer.toString(days));
		param.put("workday", workday);
		param.put("rule", "2");
		disclosureDate = disclosureWorkdayDao.findPlanCrtDate(param).get(0).getWorkday();
		return disclosureDate;
	}

	/**
	 * 功能：先删除所属月份数据再批量插入产品净值批量日期
	 * 作者：rennannan
	 * 日期：20210621
	 *
	 * @param
	 * @throws Exception
	 */
	public void addAndDelNetvalList(List<T8ProdNetvalDays> netValList, String month) throws Exception {
		T8ProdNetvalDays netvalDays = new T8ProdNetvalDays();
		netvalDays.setType("0");//批量插入
		netvalDays.setMonth(month);
		//先删除所属月份且类型为系统插入类型的数据
		t8ProdNetvalDaysDao.deleteNetvalDaysByMonth(netvalDays);
		//批量插入数据
		batchAddNetvals(netValList);
	}

	/**
	 * 功能：批量插入产品净值批量日期数据
	 * 作者：rennannan
	 * 日期：20210621
	 *
	 * @param netValList
	 * @throws Exception
	 */
	public void batchAddNetvals(List<T8ProdNetvalDays> netValList) throws Exception {
		String date = DateUtil.getNowDate();
		String time = DateUtil.getNowTime();
		for (T8ProdNetvalDays netValDays : netValList) {
			netValDays.setCrtDate(date);
			netValDays.setCrtTime(time);
			t8ProdNetvalDaysDao.addProdNetvalDays(netValDays);
		}
	}
}
