package com.kayak.schedule;

import com.kayak.server.ServerUtil;
import org.springframework.stereotype.Controller;

import java.util.HashMap;
import java.util.Map;

/**
 * com.kayak.schedule
 * user:rennannan
 * date:2021/6/22 16:52
 * function:生成产品净值披露日期   自动跑批调用
 */
@Controller
public class NetValDaysSchedule {
    public void run() {
        try {
            generateNetValDays();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * 功能：系统自动跑批，每个月28号（可配）跑下个月批量
     *
     * @throws Exception
     */
    public void generateNetValDays() throws Exception {
        Map<String, Object> param = new HashMap<String, Object>();
        // 添加到任务表
        ServerUtil.requestPost("PmsApp", "com.kayak.pms.netValue.model.T8ProdNetvalDays", "autoGenerateDays", param);
    }
}
