package com.kayak.pms.prod.model;


import com.kayak.graphql.annotation.GraphQLField;
import com.kayak.graphql.annotation.GraphQLModel;
import lombok.Data;

@Data
@GraphQLModel(fetcher = "t8ProdDeclarationService",table = "t8_prod_declara")
public class T8ProdDeclaration {
  @GraphQLField(field = "id")
  private String id;
  @GraphQLField(field = "t8_prod_info_id")
  private String t8ProdInfoId;
  @GraphQLField(field = "prod_code")
  private String prodCode;
  @GraphQLField(field = "prod_name")
  private String prodName;
  @GraphQLField(field = "org_code")
  private String orgCode;
  @GraphQLField(field = "income_characteristic")
  private String incomeCharacteristic;
  @GraphQLField(field = "prod_days")
  private String prodDays;
  @GraphQLField(field = "raise_type")
  private String raiseType;
  @GraphQLField(field = "perf_method_max")
  private String perfMethodMax;
  @GraphQLField(field = "perf_method_min")
  private String perfMethodMin;
  @GraphQLField(field = "perf_method_explain")
  private String perfMethodExplain;
  @GraphQLField(field = "prod_cur")
  private String prodCur;
  @GraphQLField(field = "redeem_cash_cur")
  private String redeemCashCur;
  @GraphQLField(field = "redeem_income_cur")
  private String redeemIncomeCur;
  @GraphQLField(field = "expe_scale")
  private String expeScale;
  @GraphQLField(field = "prod_risk_level")
  private String prodRiskLevel;
  @GraphQLField(field = "raise_start_date")
  private String raiseStartDate;
  @GraphQLField(field = "raise_end_date")
  private String raiseEndDate;
  @GraphQLField(field = "bank_prodsid")
  private String bankProdsid;
  @GraphQLField(field = "approval_name")
  private String approvalName;
  @GraphQLField(field = "approval_identif")
  private String approvalIdentif;
  @GraphQLField(field = "design_name")
  private String designName;
  @GraphQLField(field = "design_identif")
  private String designIdentif;
  @GraphQLField(field = "invest_manage_name")
  private String investManageName;
  @GraphQLField(field = "invest_manage_identif")
  private String investManageIdentif;
  @GraphQLField(field = "liaison")
  private String liaison;
  @GraphQLField(field = "liaison_tel")
  private String liaisonTel;
  @GraphQLField(field = "liaison_phone")
  private String liaisonPhone;
  @GraphQLField(field = "liaison_email")
  private String liaisonEmail;
  @GraphQLField(field = "sale_place")
  private String salePlace;
  @GraphQLField(field = "out_place_desc")
  private String outPlaceDesc;
  @GraphQLField(field = "srv_mode")
  private String srvMode;
  @GraphQLField(field = "asset_maping")
  private String assetMaping;
  @GraphQLField(field = "manage_mode")
  private String manageMode;
  @GraphQLField(field = "admin_name")
  private String adminName;
  @GraphQLField(field = "pricing_type")
  private String pricingType;
  @GraphQLField(field = "is_hold_period")
  private String isHoldPeriod;
  @GraphQLField(field = "minholdday")
  private String minholdday;
  @GraphQLField(field = "holdredeem")
  private String holdredeem;
  @GraphQLField(field = "sales_palce")
  private String salesPalce;
  @GraphQLField(field = "bord_trusti_code")
  private String bordTrustiCode;
  @GraphQLField(field = "overs_trusti_name")
  private String oversTrustiName;
  @GraphQLField(field = "overs_trusti_nation")
  private String oversTrustiNation;
  @GraphQLField(field = "preendmark")
  private String preendmark;
  @GraphQLField(field = "redeem_mark")
  private String redeemMark;
  @GraphQLField(field = "prod_brand")
  private String prodBrand;
  @GraphQLField(field = "prod_times")
  private String prodTimes;
  @GraphQLField(field = "cooperat_mode")
  private String cooperatMode;
  @GraphQLField(field = "cooperat_orgname")
  private String cooperatOrgname;
  @GraphQLField(field = "returncost")
  private String returncost;
  @GraphQLField(field = "returnincome")
  private String returnincome;
  @GraphQLField(field = "prodcreditflag")
  private String prodcreditflag;
  @GraphQLField(field = "prodcreditorg")
  private String prodcreditorg;
  @GraphQLField(field = "prodcreditmod")
  private String prodcreditmod;
  @GraphQLField(field = "prod_precent")
  private String prodPrecent;
  @GraphQLField(field = "remark")
  private String remark;
  @GraphQLField(field = "status")
  private String status;
  @GraphQLField(field = "inputuser")
  private String inputuser;
  @GraphQLField(field = "updateuser")
  private String updateuser;
  @GraphQLField(field = "crt_date")
  private String crtDate;
  @GraphQLField(field = "crt_time")
  private String crtTime;
  @GraphQLField(field = "upt_date")
  private String uptDate;
  @GraphQLField(field = "upt_time")
  private String uptTime;
}
