-- kcloud_dev.act_evt_log definition

CREATE TABLE `act_evt_log` (
  `LOG_NR_` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TYPE_` varchar(64) DEFAULT NULL COMMENT '类型',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `TIME_STAMP_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '时间',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `DATA_` longblob COMMENT '数据',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '锁定者',
  `LOCK_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定时间',
  `IS_PROCESSED_` tinyint(4) DEFAULT '0' COMMENT '是否正在执行',
  PRIMARY KEY (`LOG_NR_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件日志表';


-- kcloud_dev.act_ge_property definition

CREATE TABLE `act_ge_property` (
  `NAME_` varchar(64) NOT NULL COMMENT '名称',
  `VALUE_` varchar(300) DEFAULT NULL COMMENT '值',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  PRIMARY KEY (`NAME_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全局配置文件表';


-- kcloud_dev.act_hi_actinst definition

CREATE TABLE `act_hi_actinst` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT '1' COMMENT '版本',
  `PROC_DEF_ID_` varchar(64) NOT NULL COMMENT '流程定义ID',
  `PROC_INST_ID_` varchar(64) NOT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) NOT NULL COMMENT '执行ID',
  `ACT_ID_` varchar(255) NOT NULL COMMENT '节点ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `CALL_PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '调用外部的流程实例ID',
  `ACT_NAME_` varchar(255) DEFAULT NULL COMMENT '节点名称',
  `ACT_TYPE_` varchar(255) NOT NULL COMMENT '节点类型',
  `ASSIGNEE_` varchar(255) DEFAULT NULL COMMENT '办理人',
  `START_TIME_` datetime(3) NOT NULL COMMENT '开始时间',
  `END_TIME_` datetime(3) DEFAULT NULL COMMENT '结束时间',
  `TRANSACTION_ORDER_` int(11) DEFAULT NULL COMMENT '执行顺序',
  `DURATION_` bigint(20) DEFAULT NULL COMMENT '耗时',
  `DELETE_REASON_` varchar(4000) DEFAULT NULL COMMENT '删除原因',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户id',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_ACT_INST_START` (`START_TIME_`),
  KEY `ACT_IDX_HI_ACT_INST_END` (`END_TIME_`),
  KEY `ACT_IDX_HI_ACT_INST_PROCINST` (`PROC_INST_ID_`,`ACT_ID_`),
  KEY `ACT_IDX_HI_ACT_INST_EXEC` (`EXECUTION_ID_`,`ACT_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史节点表';


-- kcloud_dev.act_hi_attachment definition

CREATE TABLE `act_hi_attachment` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `DESCRIPTION_` varchar(4000) DEFAULT NULL COMMENT '描述',
  `TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `URL_` varchar(4000) DEFAULT NULL COMMENT '附件地址',
  `CONTENT_ID_` varchar(64) DEFAULT NULL COMMENT '字节表ID,ACT_GE_BYTEARRAY的ID',
  `TIME_` datetime(3) DEFAULT NULL COMMENT '时间',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史附件表';


-- kcloud_dev.act_hi_comment definition

CREATE TABLE `act_hi_comment` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `TIME_` datetime(3) NOT NULL COMMENT '时间',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `ACTION_` varchar(255) DEFAULT NULL COMMENT '行为类型',
  `MESSAGE_` varchar(4000) DEFAULT NULL COMMENT '基本内容',
  `FULL_MSG_` longblob COMMENT '全部内容',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史审批意见表';


-- kcloud_dev.act_hi_detail definition

CREATE TABLE `act_hi_detail` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行实例',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `ACT_INST_ID_` varchar(64) DEFAULT NULL COMMENT '节点实例ID',
  `NAME_` varchar(255) NOT NULL COMMENT '名称',
  `VAR_TYPE_` varchar(255) DEFAULT NULL COMMENT '参数类型',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `TIME_` datetime(3) NOT NULL COMMENT '时间',
  `BYTEARRAY_ID_` varchar(64) DEFAULT NULL COMMENT '字节表ID',
  `DOUBLE_` double DEFAULT NULL COMMENT '浮点值',
  `LONG_` bigint(20) DEFAULT NULL COMMENT '长整型',
  `TEXT_` varchar(4000) DEFAULT NULL COMMENT '文本值,存储变量值类型为String',
  `TEXT2_` varchar(4000) DEFAULT NULL COMMENT '字符串,此处存储的是JPA持久化对象时，才会有值。此值为对象ID\njpa变量text存className,text2存id',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_DETAIL_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_ACT_INST` (`ACT_INST_ID_`),
  KEY `ACT_IDX_HI_DETAIL_TIME` (`TIME_`),
  KEY `ACT_IDX_HI_DETAIL_NAME` (`NAME_`),
  KEY `ACT_IDX_HI_DETAIL_TASK_ID` (`TASK_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史详情表';


-- kcloud_dev.act_hi_entitylink definition

CREATE TABLE `act_hi_entitylink` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `LINK_TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `CREATE_TIME_` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `PARENT_ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '父元素ID',
  `REF_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '引用范围ID',
  `REF_SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '引用范围类型',
  `REF_SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '引用范围定义ID',
  `ROOT_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '根范围ID',
  `ROOT_SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '根范围类型',
  `HIERARCHY_TYPE_` varchar(255) DEFAULT NULL COMMENT '层次结构类型',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_ENT_LNK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_HI_ENT_LNK_REF_SCOPE` (`REF_SCOPE_ID_`,`REF_SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_HI_ENT_LNK_ROOT_SCOPE` (`ROOT_SCOPE_ID_`,`ROOT_SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_HI_ENT_LNK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`,`LINK_TYPE_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史节点表';


-- kcloud_dev.act_hi_identitylink definition

CREATE TABLE `act_hi_identitylink` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `GROUP_ID_` varchar(255) DEFAULT NULL COMMENT '用户组ID',
  `TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `CREATE_TIME_` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_USER` (`USER_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_IDENT_LNK_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_IDENT_LNK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_IDENT_LNK_TASK` (`TASK_ID_`),
  KEY `ACT_IDX_HI_IDENT_LNK_PROCINST` (`PROC_INST_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史任务人员表';


-- kcloud_dev.act_hi_procinst definition

CREATE TABLE `act_hi_procinst` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT '1' COMMENT '版本号',
  `PROC_INST_ID_` varchar(64) NOT NULL COMMENT '流程实例ID',
  `BUSINESS_KEY_` varchar(255) DEFAULT NULL COMMENT '业务主键',
  `PROC_DEF_ID_` varchar(64) NOT NULL COMMENT '流程定义ID',
  `START_TIME_` datetime(3) NOT NULL COMMENT '开始时间',
  `END_TIME_` datetime(3) DEFAULT NULL COMMENT '结束时间',
  `DURATION_` bigint(20) DEFAULT NULL COMMENT '耗时',
  `START_USER_ID_` varchar(255) DEFAULT NULL COMMENT '发起人',
  `START_ACT_ID_` varchar(255) DEFAULT NULL COMMENT '起始节点',
  `END_ACT_ID_` varchar(255) DEFAULT NULL COMMENT '结束节点',
  `SUPER_PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '父流程实例ID',
  `DELETE_REASON_` varchar(4000) DEFAULT NULL COMMENT '删除原因',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户Id',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `CALLBACK_ID_` varchar(255) DEFAULT NULL COMMENT '回调ID',
  `CALLBACK_TYPE_` varchar(255) DEFAULT NULL COMMENT '回调类型',
  `REFERENCE_ID_` varchar(255) DEFAULT NULL COMMENT '引用ID',
  `REFERENCE_TYPE_` varchar(255) DEFAULT NULL COMMENT '引用类型',
  `PROPAGATED_STAGE_INST_ID_` varchar(255) DEFAULT NULL COMMENT '传播阶段实例ID',
  `BUSINESS_STATUS_` varchar(255) DEFAULT NULL COMMENT '业务状态',
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `PROC_INST_ID_` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_PRO_INST_END` (`END_TIME_`),
  KEY `ACT_IDX_HI_PRO_I_BUSKEY` (`BUSINESS_KEY_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史流程实例表';


-- kcloud_dev.act_hi_taskinst definition

CREATE TABLE `act_hi_taskinst` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT '1' COMMENT '版本号',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `TASK_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '任务定义ID',
  `TASK_DEF_KEY_` varchar(255) DEFAULT NULL COMMENT '任务定义KEY',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `PROPAGATED_STAGE_INST_ID_` varchar(255) DEFAULT NULL COMMENT '传播阶段实例ID',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `PARENT_TASK_ID_` varchar(64) DEFAULT NULL COMMENT '父任务ID',
  `DESCRIPTION_` varchar(4000) DEFAULT NULL COMMENT '说明',
  `OWNER_` varchar(255) DEFAULT NULL COMMENT '实际签收人 任务的拥有者',
  `ASSIGNEE_` varchar(255) DEFAULT NULL COMMENT '办理人',
  `START_TIME_` datetime(3) NOT NULL COMMENT '开始时间',
  `CLAIM_TIME_` datetime(3) DEFAULT NULL COMMENT '认领时间',
  `END_TIME_` datetime(3) DEFAULT NULL COMMENT '结束时间',
  `DURATION_` bigint(20) DEFAULT NULL COMMENT '耗时',
  `DELETE_REASON_` varchar(4000) DEFAULT NULL COMMENT '删除原因',
  `PRIORITY_` int(11) DEFAULT NULL COMMENT '优先级别',
  `DUE_DATE_` datetime(3) DEFAULT NULL COMMENT '过期时间',
  `FORM_KEY_` varchar(255) DEFAULT NULL COMMENT '节点定义的formkey',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  `LAST_UPDATED_TIME_` datetime(3) DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_TASK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_TASK_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_TASK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_TASK_INST_PROCINST` (`PROC_INST_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史任务实例表';


-- kcloud_dev.act_hi_tsk_log definition

CREATE TABLE `act_hi_tsk_log` (
  `ID_` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `TYPE_` varchar(64) DEFAULT NULL COMMENT '类型',
  `TASK_ID_` varchar(64) NOT NULL COMMENT '任务ID',
  `TIME_STAMP_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '时间',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `DATA_` varchar(4000) DEFAULT NULL COMMENT '日期',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务变更日志';


-- kcloud_dev.act_hi_varinst definition

CREATE TABLE `act_hi_varinst` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT '1' COMMENT '版本号',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `NAME_` varchar(255) NOT NULL COMMENT '名称',
  `VAR_TYPE_` varchar(100) DEFAULT NULL COMMENT '参数类型',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `BYTEARRAY_ID_` varchar(64) DEFAULT NULL COMMENT '字节表ID',
  `DOUBLE_` double DEFAULT NULL COMMENT '存储double类型数据',
  `LONG_` bigint(20) DEFAULT NULL COMMENT '存储long类型数据',
  `TEXT_` varchar(4000) DEFAULT NULL COMMENT '存储string类型数据',
  `TEXT2_` varchar(4000) DEFAULT NULL COMMENT '存储文本类型数据',
  `CREATE_TIME_` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATED_TIME_` datetime(3) DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_HI_PROCVAR_NAME_TYPE` (`NAME_`,`VAR_TYPE_`),
  KEY `ACT_IDX_HI_VAR_SCOPE_ID_TYPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_VAR_SUB_ID_TYPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_HI_PROCVAR_PROC_INST` (`PROC_INST_ID_`),
  KEY `ACT_IDX_HI_PROCVAR_TASK_ID` (`TASK_ID_`),
  KEY `ACT_IDX_HI_PROCVAR_EXE` (`EXECUTION_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史流程变量表';


-- kcloud_dev.act_re_deployment definition

CREATE TABLE `act_re_deployment` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '分类',
  `KEY_` varchar(255) DEFAULT NULL COMMENT '标志',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  `DEPLOY_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '部署时间',
  `DERIVED_FROM_` varchar(64) DEFAULT NULL COMMENT '直接派生自哪次部署',
  `DERIVED_FROM_ROOT_` varchar(64) DEFAULT NULL COMMENT '派生的根部署',
  `PARENT_DEPLOYMENT_ID_` varchar(255) DEFAULT NULL COMMENT '父部署的ID',
  `ENGINE_VERSION_` varchar(255) DEFAULT NULL COMMENT '流程引擎的版本',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部署信息表';


-- kcloud_dev.act_re_procdef definition

CREATE TABLE `act_re_procdef` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '分类',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `KEY_` varchar(255) NOT NULL COMMENT '标识',
  `VERSION_` int(11) NOT NULL COMMENT '版本',
  `DEPLOYMENT_ID_` varchar(64) DEFAULT NULL COMMENT '部署ID',
  `RESOURCE_NAME_` varchar(4000) DEFAULT NULL COMMENT '资源名称',
  `DGRM_RESOURCE_NAME_` varchar(4000) DEFAULT NULL COMMENT '图片资源名称',
  `DESCRIPTION_` varchar(4000) DEFAULT NULL COMMENT '描述',
  `HAS_START_FORM_KEY_` tinyint(4) DEFAULT NULL COMMENT '拥有开始表单标识',
  `HAS_GRAPHICAL_NOTATION_` tinyint(4) DEFAULT NULL COMMENT '拥有图形信息',
  `SUSPENSION_STATE_` int(11) DEFAULT NULL COMMENT '挂起状态',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  `ENGINE_VERSION_` varchar(255) DEFAULT NULL COMMENT '流程引擎版本',
  `DERIVED_FROM_` varchar(64) DEFAULT NULL COMMENT '直接派生自哪次部署',
  `DERIVED_FROM_ROOT_` varchar(64) DEFAULT NULL COMMENT '派生的根部署',
  `DERIVED_VERSION_` int(11) NOT NULL DEFAULT '0' COMMENT '派生自哪个版本',
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `ACT_UNIQ_PROCDEF` (`KEY_`,`VERSION_`,`DERIVED_VERSION_`,`TENANT_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义表';


-- kcloud_dev.act_ru_actinst definition

CREATE TABLE `act_ru_actinst` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT '1' COMMENT '版本号',
  `PROC_DEF_ID_` varchar(64) NOT NULL COMMENT '流程定义ID',
  `PROC_INST_ID_` varchar(64) NOT NULL COMMENT '流程实例ID',
  `EXECUTION_ID_` varchar(64) NOT NULL COMMENT '执行ID',
  `ACT_ID_` varchar(255) NOT NULL COMMENT '节点ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `CALL_PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '调用流程实例ID',
  `ACT_NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `ACT_TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `ASSIGNEE_` varchar(255) DEFAULT NULL COMMENT '办理人',
  `START_TIME_` datetime(3) NOT NULL COMMENT '开始时间',
  `END_TIME_` datetime(3) DEFAULT NULL COMMENT '结束时间',
  `DURATION_` bigint(20) DEFAULT NULL COMMENT '耗时',
  `TRANSACTION_ORDER_` int(11) DEFAULT NULL COMMENT '执行顺序',
  `DELETE_REASON_` varchar(4000) DEFAULT NULL COMMENT '删除原因',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户id',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_RU_ACTI_START` (`START_TIME_`),
  KEY `ACT_IDX_RU_ACTI_END` (`END_TIME_`),
  KEY `ACT_IDX_RU_ACTI_PROC` (`PROC_INST_ID_`),
  KEY `ACT_IDX_RU_ACTI_PROC_ACT` (`PROC_INST_ID_`,`ACT_ID_`),
  KEY `ACT_IDX_RU_ACTI_EXEC` (`EXECUTION_ID_`),
  KEY `ACT_IDX_RU_ACTI_EXEC_ACT` (`EXECUTION_ID_`,`ACT_ID_`),
  KEY `ACT_IDX_RU_ACTI_TASK` (`TASK_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='正在运行的节点表';


-- kcloud_dev.act_ru_entitylink definition

CREATE TABLE `act_ru_entitylink` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CREATE_TIME_` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `LINK_TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `PARENT_ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '父元素ID',
  `REF_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '引用范围ID',
  `REF_SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '引用范围类型',
  `REF_SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '引用范围定义ID',
  `ROOT_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '根范围ID',
  `ROOT_SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '根范围类型',
  `HIERARCHY_TYPE_` varchar(255) DEFAULT NULL COMMENT '结构层次类型',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_ENT_LNK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_ENT_LNK_REF_SCOPE` (`REF_SCOPE_ID_`,`REF_SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_ENT_LNK_ROOT_SCOPE` (`ROOT_SCOPE_ID_`,`ROOT_SCOPE_TYPE_`,`LINK_TYPE_`),
  KEY `ACT_IDX_ENT_LNK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`,`LINK_TYPE_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时节点人员表';


-- kcloud_dev.act_ru_history_job definition

CREATE TABLE `act_ru_history_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `LOCK_EXP_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定过期时间',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '锁定人',
  `RETRIES_` int(11) DEFAULT NULL COMMENT '重试',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常信息ID',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值IDs',
  `ADV_HANDLER_CFG_ID_` varchar(64) DEFAULT NULL COMMENT '处理配置ID',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史作业表';


-- kcloud_dev.flw_channel_definition definition

CREATE TABLE `flw_channel_definition` (
  `ID_` varchar(255) NOT NULL COMMENT '主键',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `VERSION_` int(11) DEFAULT NULL COMMENT '版本',
  `KEY_` varchar(255) DEFAULT NULL COMMENT '标志',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `DEPLOYMENT_ID_` varchar(255) DEFAULT NULL COMMENT '部署ID',
  `CREATE_TIME_` datetime(3) DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT NULL COMMENT '租户ID',
  `RESOURCE_NAME_` varchar(255) DEFAULT NULL COMMENT '资源名称',
  `DESCRIPTION_` varchar(255) DEFAULT NULL COMMENT '描述',
  `TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `IMPLEMENTATION_` varchar(255) DEFAULT NULL COMMENT '实施',
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `ACT_IDX_CHANNEL_DEF_UNIQ` (`KEY_`,`VERSION_`,`TENANT_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泳池管道定义表';


-- kcloud_dev.flw_ev_databasechangelog definition

CREATE TABLE `flw_ev_databasechangelog` (
  `ID` varchar(255) NOT NULL COMMENT '主键',
  `AUTHOR` varchar(255) NOT NULL COMMENT '作者',
  `FILENAME` varchar(255) NOT NULL COMMENT '名称',
  `DATEEXECUTED` datetime NOT NULL COMMENT '执行日期',
  `ORDEREXECUTED` int(11) NOT NULL COMMENT '执行顺序',
  `EXECTYPE` varchar(10) NOT NULL COMMENT '执行类型',
  `MD5SUM` varchar(35) DEFAULT NULL COMMENT 'MD5',
  `DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '描述',
  `COMMENTS` varchar(255) DEFAULT NULL COMMENT '注释',
  `TAG` varchar(255) DEFAULT NULL COMMENT '标签',
  `LIQUIBASE` varchar(20) DEFAULT NULL COMMENT 'LIQUIBASE版本',
  `CONTEXTS` varchar(255) DEFAULT NULL COMMENT '内容',
  `LABELS` varchar(255) DEFAULT NULL COMMENT '标签',
  `DEPLOYMENT_ID` varchar(10) DEFAULT NULL COMMENT '部署ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Liquibase执行的记录表';


-- kcloud_dev.flw_ev_databasechangeloglock definition

CREATE TABLE `flw_ev_databasechangeloglock` (
  `ID` int(11) NOT NULL COMMENT '主键',
  `LOCKED` bit(1) NOT NULL COMMENT '是否锁定',
  `LOCKGRANTED` datetime DEFAULT NULL COMMENT '已授予锁定',
  `LOCKEDBY` varchar(255) DEFAULT NULL COMMENT '被谁锁定',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Liquibase执行锁';


-- kcloud_dev.flw_event_definition definition

CREATE TABLE `flw_event_definition` (
  `ID_` varchar(255) NOT NULL COMMENT '主键',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `VERSION_` int(11) DEFAULT NULL COMMENT '版本',
  `KEY_` varchar(255) DEFAULT NULL COMMENT '标识',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `DEPLOYMENT_ID_` varchar(255) DEFAULT NULL COMMENT '部署ID',
  `TENANT_ID_` varchar(255) DEFAULT NULL COMMENT '租户ID',
  `RESOURCE_NAME_` varchar(255) DEFAULT NULL COMMENT '资源名称',
  `DESCRIPTION_` varchar(255) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `ACT_IDX_EVENT_DEF_UNIQ` (`KEY_`,`VERSION_`,`TENANT_ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件定义表';


-- kcloud_dev.flw_event_deployment definition

CREATE TABLE `flw_event_deployment` (
  `ID_` varchar(255) NOT NULL COMMENT '主键',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `DEPLOY_TIME_` datetime(3) DEFAULT NULL COMMENT '部署时间',
  `TENANT_ID_` varchar(255) DEFAULT NULL COMMENT '租户ID',
  `PARENT_DEPLOYMENT_ID_` varchar(255) DEFAULT NULL COMMENT '父部署ID',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件部署表';


-- kcloud_dev.flw_event_resource definition

CREATE TABLE `flw_event_resource` (
  `ID_` varchar(255) NOT NULL COMMENT '主键',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `DEPLOYMENT_ID_` varchar(255) DEFAULT NULL COMMENT '部署ID',
  `RESOURCE_BYTES_` longblob COMMENT '资源的二进制数据',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件资源表';


-- kcloud_dev.flw_ru_batch definition

CREATE TABLE `flw_ru_batch` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `TYPE_` varchar(64) NOT NULL COMMENT '类型',
  `SEARCH_KEY_` varchar(255) DEFAULT NULL COMMENT '搜索关键字1',
  `SEARCH_KEY2_` varchar(255) DEFAULT NULL COMMENT '搜索关键字2',
  `CREATE_TIME_` datetime(3) NOT NULL COMMENT '创建时间',
  `COMPLETE_TIME_` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `STATUS_` varchar(255) DEFAULT NULL COMMENT '状态',
  `BATCH_DOC_ID_` varchar(64) DEFAULT NULL COMMENT '批量迁移文档ID',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批量迁移表';


-- kcloud_dev.act_ge_bytearray definition

CREATE TABLE `act_ge_bytearray` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `DEPLOYMENT_ID_` varchar(64) DEFAULT NULL COMMENT '部署ID',
  `BYTES_` longblob COMMENT '字节（二进制数据',
  `GENERATED_` tinyint(4) DEFAULT NULL COMMENT '是否系统生成',
  PRIMARY KEY (`ID_`),
  KEY `ACT_FK_BYTEARR_DEPL` (`DEPLOYMENT_ID_`),
  CONSTRAINT `ACT_FK_BYTEARR_DEPL` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `act_re_deployment` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='二进制文件表';


-- kcloud_dev.act_procdef_info definition

CREATE TABLE `act_procdef_info` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `PROC_DEF_ID_` varchar(64) NOT NULL COMMENT '流程定义ID',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `INFO_JSON_ID_` varchar(64) DEFAULT NULL COMMENT '内容',
  PRIMARY KEY (`ID_`),
  UNIQUE KEY `ACT_UNIQ_INFO_PROCDEF` (`PROC_DEF_ID_`),
  KEY `ACT_IDX_INFO_PROCDEF` (`PROC_DEF_ID_`),
  KEY `ACT_FK_INFO_JSON_BA` (`INFO_JSON_ID_`),
  CONSTRAINT `ACT_FK_INFO_JSON_BA` FOREIGN KEY (`INFO_JSON_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_INFO_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义更新信息';


-- kcloud_dev.act_re_model definition

CREATE TABLE `act_re_model` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `KEY_` varchar(255) DEFAULT NULL COMMENT '标识',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '分类',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '最后更新时间',
  `VERSION_` int(11) DEFAULT NULL COMMENT '版本',
  `META_INFO_` varchar(4000) DEFAULT NULL COMMENT '元数据，以json格式保存流程定义的信息',
  `DEPLOYMENT_ID_` varchar(64) DEFAULT NULL COMMENT '部署ID',
  `EDITOR_SOURCE_VALUE_ID_` varchar(64) DEFAULT NULL COMMENT '二进制文件ID，设计器原始信息',
  `EDITOR_SOURCE_EXTRA_VALUE_ID_` varchar(64) DEFAULT NULL COMMENT '二进制文件ID，设计器扩展信息',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_FK_MODEL_SOURCE` (`EDITOR_SOURCE_VALUE_ID_`),
  KEY `ACT_FK_MODEL_SOURCE_EXTRA` (`EDITOR_SOURCE_EXTRA_VALUE_ID_`),
  KEY `ACT_FK_MODEL_DEPLOYMENT` (`DEPLOYMENT_ID_`),
  CONSTRAINT `ACT_FK_MODEL_DEPLOYMENT` FOREIGN KEY (`DEPLOYMENT_ID_`) REFERENCES `act_re_deployment` (`ID_`),
  CONSTRAINT `ACT_FK_MODEL_SOURCE` FOREIGN KEY (`EDITOR_SOURCE_VALUE_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_MODEL_SOURCE_EXTRA` FOREIGN KEY (`EDITOR_SOURCE_EXTRA_VALUE_ID_`) REFERENCES `act_ge_bytearray` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程设计模型部署表';


-- kcloud_dev.act_ru_execution definition

CREATE TABLE `act_ru_execution` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `BUSINESS_KEY_` varchar(255) DEFAULT NULL COMMENT '业务主键',
  `PARENT_ID_` varchar(64) DEFAULT NULL COMMENT '父级ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `SUPER_EXEC_` varchar(64) DEFAULT NULL COMMENT '父流程实例中对应的执行',
  `ROOT_PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '根流程实例ID',
  `ACT_ID_` varchar(255) DEFAULT NULL COMMENT '节点ID',
  `IS_ACTIVE_` tinyint(4) DEFAULT NULL COMMENT '是否激活',
  `IS_CONCURRENT_` tinyint(4) DEFAULT NULL COMMENT '是否分支（并行）',
  `IS_SCOPE_` tinyint(4) DEFAULT NULL COMMENT '是否处于多实例或环节嵌套状态',
  `IS_EVENT_SCOPE_` tinyint(4) DEFAULT NULL COMMENT '是否激活状态',
  `IS_MI_ROOT_` tinyint(4) DEFAULT NULL COMMENT '是否根实例',
  `SUSPENSION_STATE_` int(11) DEFAULT NULL COMMENT '挂起状态',
  `CACHED_ENT_STATE_` int(11) DEFAULT NULL COMMENT '缓存状态',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `START_ACT_ID_` varchar(255) DEFAULT NULL COMMENT '开始节点ID',
  `START_TIME_` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `START_USER_ID_` varchar(255) DEFAULT NULL COMMENT '发起用户',
  `LOCK_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定时间',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '锁定者',
  `IS_COUNT_ENABLED_` tinyint(4) DEFAULT NULL COMMENT '是否计数',
  `EVT_SUBSCR_COUNT_` int(11) DEFAULT NULL COMMENT '事件订阅数',
  `TASK_COUNT_` int(11) DEFAULT NULL COMMENT '任务数',
  `JOB_COUNT_` int(11) DEFAULT NULL COMMENT '作业数',
  `TIMER_JOB_COUNT_` int(11) DEFAULT NULL COMMENT '定时作业数',
  `SUSP_JOB_COUNT_` int(11) DEFAULT NULL COMMENT '暂停作业数',
  `DEADLETTER_JOB_COUNT_` int(11) DEFAULT NULL COMMENT '无法执行作业数',
  `EXTERNAL_WORKER_JOB_COUNT_` int(11) DEFAULT NULL COMMENT '外部作业数',
  `VAR_COUNT_` int(11) DEFAULT NULL COMMENT '变量数',
  `ID_LINK_COUNT_` int(11) DEFAULT NULL COMMENT '人员数',
  `CALLBACK_ID_` varchar(255) DEFAULT NULL COMMENT '回调ID',
  `CALLBACK_TYPE_` varchar(255) DEFAULT NULL COMMENT '回调类型',
  `REFERENCE_ID_` varchar(255) DEFAULT NULL COMMENT '引用ID',
  `REFERENCE_TYPE_` varchar(255) DEFAULT NULL COMMENT '引用类型',
  `PROPAGATED_STAGE_INST_ID_` varchar(255) DEFAULT NULL COMMENT '传播阶段实例ID',
  `BUSINESS_STATUS_` varchar(255) DEFAULT NULL COMMENT '业务状态',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_EXEC_BUSKEY` (`BUSINESS_KEY_`),
  KEY `ACT_IDC_EXEC_ROOT` (`ROOT_PROC_INST_ID_`),
  KEY `ACT_IDX_EXEC_REF_ID_` (`REFERENCE_ID_`),
  KEY `ACT_FK_EXE_PROCINST` (`PROC_INST_ID_`),
  KEY `ACT_FK_EXE_PARENT` (`PARENT_ID_`),
  KEY `ACT_FK_EXE_SUPER` (`SUPER_EXEC_`),
  KEY `ACT_FK_EXE_PROCDEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_EXE_PARENT` FOREIGN KEY (`PARENT_ID_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE,
  CONSTRAINT `ACT_FK_EXE_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),
  CONSTRAINT `ACT_FK_EXE_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ACT_FK_EXE_SUPER` FOREIGN KEY (`SUPER_EXEC_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时执行表';


-- kcloud_dev.act_ru_external_job definition

CREATE TABLE `act_ru_external_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `LOCK_EXP_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定过期时间',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '锁定人',
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL COMMENT '是否排他作业',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '元素ID',
  `ELEMENT_NAME_` varchar(255) DEFAULT NULL COMMENT '元素名',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `CORRELATION_ID_` varchar(255) DEFAULT NULL COMMENT '相关性ID',
  `RETRIES_` int(11) DEFAULT NULL COMMENT '重试',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常信息ID',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL COMMENT '过期时间',
  `REPEAT_` varchar(255) DEFAULT NULL COMMENT '重复',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值ID',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_EXTERNAL_JOB_EXCEPTION_STACK_ID` (`EXCEPTION_STACK_ID_`),
  KEY `ACT_IDX_EXTERNAL_JOB_CUSTOM_VALUES_ID` (`CUSTOM_VALUES_ID_`),
  KEY `ACT_IDX_EXTERNAL_JOB_CORRELATION_ID` (`CORRELATION_ID_`),
  KEY `ACT_IDX_EJOB_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_EJOB_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_EJOB_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  CONSTRAINT `ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES` FOREIGN KEY (`CUSTOM_VALUES_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_EXTERNAL_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时外部作业表';


-- kcloud_dev.act_ru_job definition

CREATE TABLE `act_ru_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `LOCK_EXP_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定过期时间',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '挂起者',
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL COMMENT '是否唯一',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行实例ID',
  `PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '元素ID',
  `ELEMENT_NAME_` varchar(255) DEFAULT NULL COMMENT '元素名',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `CORRELATION_ID_` varchar(255) DEFAULT NULL COMMENT '相关性ID',
  `RETRIES_` int(11) DEFAULT NULL COMMENT '重试',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常堆栈',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL COMMENT '截止时间',
  `REPEAT_` varchar(255) DEFAULT NULL COMMENT '重复',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理器类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理器配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值IDs',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_JOB_EXCEPTION_STACK_ID` (`EXCEPTION_STACK_ID_`),
  KEY `ACT_IDX_JOB_CUSTOM_VALUES_ID` (`CUSTOM_VALUES_ID_`),
  KEY `ACT_IDX_JOB_CORRELATION_ID` (`CORRELATION_ID_`),
  KEY `ACT_IDX_JOB_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_JOB_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_JOB_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_JOB_EXECUTION` (`EXECUTION_ID_`),
  KEY `ACT_FK_JOB_PROCESS_INSTANCE` (`PROCESS_INSTANCE_ID_`),
  KEY `ACT_FK_JOB_PROC_DEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_JOB_CUSTOM_VALUES` FOREIGN KEY (`CUSTOM_VALUES_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_JOB_EXECUTION` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_JOB_PROCESS_INSTANCE` FOREIGN KEY (`PROCESS_INSTANCE_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_JOB_PROC_DEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时作业表';


-- kcloud_dev.act_ru_suspended_job definition

CREATE TABLE `act_ru_suspended_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL COMMENT '排他作业',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '元素ID',
  `ELEMENT_NAME_` varchar(255) DEFAULT NULL COMMENT '元素名',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `CORRELATION_ID_` varchar(255) DEFAULT NULL COMMENT '相关性ID',
  `RETRIES_` int(11) DEFAULT NULL COMMENT '重试',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常信息ID',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL COMMENT '过期时间',
  `REPEAT_` varchar(255) DEFAULT NULL COMMENT '重复',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值ID',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_SUSPENDED_JOB_EXCEPTION_STACK_ID` (`EXCEPTION_STACK_ID_`),
  KEY `ACT_IDX_SUSPENDED_JOB_CUSTOM_VALUES_ID` (`CUSTOM_VALUES_ID_`),
  KEY `ACT_IDX_SUSPENDED_JOB_CORRELATION_ID` (`CORRELATION_ID_`),
  KEY `ACT_IDX_SJOB_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_SJOB_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_SJOB_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_SUSPENDED_JOB_EXECUTION` (`EXECUTION_ID_`),
  KEY `ACT_FK_SUSPENDED_JOB_PROCESS_INSTANCE` (`PROCESS_INSTANCE_ID_`),
  KEY `ACT_FK_SUSPENDED_JOB_PROC_DEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES` FOREIGN KEY (`CUSTOM_VALUES_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_SUSPENDED_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_SUSPENDED_JOB_EXECUTION` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_SUSPENDED_JOB_PROCESS_INSTANCE` FOREIGN KEY (`PROCESS_INSTANCE_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_SUSPENDED_JOB_PROC_DEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='暂停作业表';


-- kcloud_dev.act_ru_task definition

CREATE TABLE `act_ru_task` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行实例ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `TASK_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '任务定义ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `PROPAGATED_STAGE_INST_ID_` varchar(255) DEFAULT NULL COMMENT '传播阶段实例IDs',
  `NAME_` varchar(255) DEFAULT NULL COMMENT '名称',
  `PARENT_TASK_ID_` varchar(64) DEFAULT NULL COMMENT '父任务ID',
  `DESCRIPTION_` varchar(4000) DEFAULT NULL COMMENT '描述',
  `TASK_DEF_KEY_` varchar(255) DEFAULT NULL COMMENT '任务定义KEY',
  `OWNER_` varchar(255) DEFAULT NULL COMMENT '被代理人',
  `ASSIGNEE_` varchar(255) DEFAULT NULL COMMENT '办理人',
  `DELEGATION_` varchar(64) DEFAULT NULL COMMENT '委托状态',
  `PRIORITY_` int(11) DEFAULT NULL COMMENT '优先级',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `DUE_DATE_` datetime(3) DEFAULT NULL COMMENT '截止时间',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '分类',
  `SUSPENSION_STATE_` int(11) DEFAULT NULL COMMENT '挂起状态',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  `FORM_KEY_` varchar(255) DEFAULT NULL COMMENT '表单标识',
  `CLAIM_TIME_` datetime(3) DEFAULT NULL COMMENT '认领时间',
  `IS_COUNT_ENABLED_` tinyint(4) DEFAULT NULL COMMENT '是否计数',
  `VAR_COUNT_` int(11) DEFAULT NULL COMMENT '变量数',
  `ID_LINK_COUNT_` int(11) DEFAULT NULL COMMENT '相关用户数',
  `SUB_TASK_COUNT_` int(11) DEFAULT NULL COMMENT '子任务数',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_TASK_CREATE` (`CREATE_TIME_`),
  KEY `ACT_IDX_TASK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_TASK_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_TASK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_TASK_EXE` (`EXECUTION_ID_`),
  KEY `ACT_FK_TASK_PROCINST` (`PROC_INST_ID_`),
  KEY `ACT_FK_TASK_PROCDEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_TASK_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_TASK_PROCDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),
  CONSTRAINT `ACT_FK_TASK_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运作中任务表';


-- kcloud_dev.act_ru_timer_job definition

CREATE TABLE `act_ru_timer_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `LOCK_EXP_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '锁定过期时间',
  `LOCK_OWNER_` varchar(255) DEFAULT NULL COMMENT '锁定人',
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL COMMENT '排他作业',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '元素ID',
  `ELEMENT_NAME_` varchar(255) DEFAULT NULL COMMENT '元素名',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `CORRELATION_ID_` varchar(255) DEFAULT NULL COMMENT '相关性ID',
  `RETRIES_` int(11) DEFAULT NULL COMMENT '重试',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常信息ID',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL COMMENT '过去时间',
  `REPEAT_` varchar(255) DEFAULT NULL COMMENT '重复',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值ID',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_TIMER_JOB_EXCEPTION_STACK_ID` (`EXCEPTION_STACK_ID_`),
  KEY `ACT_IDX_TIMER_JOB_CUSTOM_VALUES_ID` (`CUSTOM_VALUES_ID_`),
  KEY `ACT_IDX_TIMER_JOB_CORRELATION_ID` (`CORRELATION_ID_`),
  KEY `ACT_IDX_TIMER_JOB_DUEDATE` (`DUEDATE_`),
  KEY `ACT_IDX_TJOB_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_TJOB_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_TJOB_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_TIMER_JOB_EXECUTION` (`EXECUTION_ID_`),
  KEY `ACT_FK_TIMER_JOB_PROCESS_INSTANCE` (`PROCESS_INSTANCE_ID_`),
  KEY `ACT_FK_TIMER_JOB_PROC_DEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_TIMER_JOB_CUSTOM_VALUES` FOREIGN KEY (`CUSTOM_VALUES_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_TIMER_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_TIMER_JOB_EXECUTION` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_TIMER_JOB_PROCESS_INSTANCE` FOREIGN KEY (`PROCESS_INSTANCE_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_TIMER_JOB_PROC_DEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时定时作业表';


-- kcloud_dev.act_ru_variable definition

CREATE TABLE `act_ru_variable` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `NAME_` varchar(255) NOT NULL COMMENT '名称',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行实例ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `BYTEARRAY_ID_` varchar(64) DEFAULT NULL COMMENT '资源ID',
  `DOUBLE_` double DEFAULT NULL COMMENT '浮点值',
  `LONG_` bigint(20) DEFAULT NULL COMMENT '长整型',
  `TEXT_` varchar(4000) DEFAULT NULL COMMENT '文本值，存储变量值类型为String 如此处存储持久化对象时，值jpa对象的class',
  `TEXT2_` varchar(4000) DEFAULT NULL COMMENT '文本值，此处存储的是JPA持久化对象时，才会有值。此值为对象ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_RU_VAR_SCOPE_ID_TYPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_RU_VAR_SUB_ID_TYPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_VAR_BYTEARRAY` (`BYTEARRAY_ID_`),
  KEY `ACT_IDX_VARIABLE_TASK_ID` (`TASK_ID_`),
  KEY `ACT_FK_VAR_EXE` (`EXECUTION_ID_`),
  KEY `ACT_FK_VAR_PROCINST` (`PROC_INST_ID_`),
  CONSTRAINT `ACT_FK_VAR_BYTEARRAY` FOREIGN KEY (`BYTEARRAY_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_VAR_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运行时变量表';


-- kcloud_dev.flw_ru_batch_part definition

CREATE TABLE `flw_ru_batch_part` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `BATCH_ID_` varchar(64) DEFAULT NULL COMMENT '批量迁移ID',
  `TYPE_` varchar(64) NOT NULL COMMENT '类型',
  `SCOPE_ID_` varchar(64) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(64) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(64) DEFAULT NULL COMMENT '范围类型',
  `SEARCH_KEY_` varchar(255) DEFAULT NULL COMMENT '搜索关键字1',
  `SEARCH_KEY2_` varchar(255) DEFAULT NULL COMMENT '搜索关键字2',
  `CREATE_TIME_` datetime(3) NOT NULL COMMENT '创建时间',
  `COMPLETE_TIME_` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `STATUS_` varchar(255) DEFAULT NULL COMMENT '状态',
  `RESULT_DOC_ID_` varchar(64) DEFAULT NULL COMMENT '结果文档Id',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `FLW_IDX_BATCH_PART` (`BATCH_ID_`),
  CONSTRAINT `FLW_FK_BATCH_PART_PARENT` FOREIGN KEY (`BATCH_ID_`) REFERENCES `flw_ru_batch` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批量迁移模块表';


-- kcloud_dev.act_ru_deadletter_job definition

CREATE TABLE `act_ru_deadletter_job` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `CATEGORY_` varchar(255) DEFAULT NULL COMMENT '类别',
  `TYPE_` varchar(255) NOT NULL COMMENT '类型',
  `EXCLUSIVE_` tinyint(1) DEFAULT NULL COMMENT '是否排他作业',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROCESS_INSTANCE_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `ELEMENT_ID_` varchar(255) DEFAULT NULL COMMENT '元素ID',
  `ELEMENT_NAME_` varchar(255) DEFAULT NULL COMMENT '元素名称',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  `CORRELATION_ID_` varchar(255) DEFAULT NULL COMMENT '相关性ID',
  `EXCEPTION_STACK_ID_` varchar(64) DEFAULT NULL COMMENT '异常信息ID',
  `EXCEPTION_MSG_` varchar(4000) DEFAULT NULL COMMENT '异常信息',
  `DUEDATE_` timestamp(3) NULL DEFAULT NULL COMMENT '到期时间',
  `REPEAT_` varchar(255) DEFAULT NULL COMMENT '重复',
  `HANDLER_TYPE_` varchar(255) DEFAULT NULL COMMENT '处理类型',
  `HANDLER_CFG_` varchar(4000) DEFAULT NULL COMMENT '处理配置',
  `CUSTOM_VALUES_ID_` varchar(64) DEFAULT NULL COMMENT '自定义值ID',
  `CREATE_TIME_` timestamp(3) NULL DEFAULT NULL COMMENT '创建时间',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_DEADLETTER_JOB_EXCEPTION_STACK_ID` (`EXCEPTION_STACK_ID_`),
  KEY `ACT_IDX_DEADLETTER_JOB_CUSTOM_VALUES_ID` (`CUSTOM_VALUES_ID_`),
  KEY `ACT_IDX_DEADLETTER_JOB_CORRELATION_ID` (`CORRELATION_ID_`),
  KEY `ACT_IDX_DJOB_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_DJOB_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_DJOB_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_FK_DEADLETTER_JOB_EXECUTION` (`EXECUTION_ID_`),
  KEY `ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE` (`PROCESS_INSTANCE_ID_`),
  KEY `ACT_FK_DEADLETTER_JOB_PROC_DEF` (`PROC_DEF_ID_`),
  CONSTRAINT `ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES` FOREIGN KEY (`CUSTOM_VALUES_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_DEADLETTER_JOB_EXCEPTION` FOREIGN KEY (`EXCEPTION_STACK_ID_`) REFERENCES `act_ge_bytearray` (`ID_`),
  CONSTRAINT `ACT_FK_DEADLETTER_JOB_EXECUTION` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_DEADLETTER_JOB_PROCESS_INSTANCE` FOREIGN KEY (`PROCESS_INSTANCE_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_DEADLETTER_JOB_PROC_DEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='无法执行工作表';


-- kcloud_dev.act_ru_event_subscr definition

CREATE TABLE `act_ru_event_subscr` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本',
  `EVENT_TYPE_` varchar(255) NOT NULL COMMENT '事件类型',
  `EVENT_NAME_` varchar(255) DEFAULT NULL COMMENT '事件名称',
  `EXECUTION_ID_` varchar(64) DEFAULT NULL COMMENT '执行ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `ACTIVITY_ID_` varchar(64) DEFAULT NULL COMMENT '具体事件ID',
  `CONFIGURATION_` varchar(255) DEFAULT NULL COMMENT '事件的配置属性',
  `CREATED_` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `SUB_SCOPE_ID_` varchar(64) DEFAULT NULL COMMENT '子范围定义ID',
  `SCOPE_ID_` varchar(64) DEFAULT NULL COMMENT '范围ID',
  `SCOPE_DEFINITION_ID_` varchar(64) DEFAULT NULL COMMENT '范围定义ID',
  `SCOPE_TYPE_` varchar(64) DEFAULT NULL COMMENT '范围类型',
  `TENANT_ID_` varchar(255) DEFAULT '' COMMENT '租户ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_EVENT_SUBSCR_CONFIG_` (`CONFIGURATION_`),
  KEY `ACT_FK_EVENT_EXEC` (`EXECUTION_ID_`),
  CONSTRAINT `ACT_FK_EVENT_EXEC` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件订阅表';


-- kcloud_dev.act_ru_identitylink definition

CREATE TABLE `act_ru_identitylink` (
  `ID_` varchar(64) NOT NULL COMMENT '主键',
  `REV_` int(11) DEFAULT NULL COMMENT '版本号',
  `GROUP_ID_` varchar(255) DEFAULT NULL COMMENT '用户组ID',
  `TYPE_` varchar(255) DEFAULT NULL COMMENT '类型',
  `USER_ID_` varchar(255) DEFAULT NULL COMMENT '用户ID',
  `TASK_ID_` varchar(64) DEFAULT NULL COMMENT '任务ID',
  `PROC_INST_ID_` varchar(64) DEFAULT NULL COMMENT '流程实例ID',
  `PROC_DEF_ID_` varchar(64) DEFAULT NULL COMMENT '流程定义ID',
  `SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '范围ID',
  `SUB_SCOPE_ID_` varchar(255) DEFAULT NULL COMMENT '子范围ID',
  `SCOPE_TYPE_` varchar(255) DEFAULT NULL COMMENT '范围类型',
  `SCOPE_DEFINITION_ID_` varchar(255) DEFAULT NULL COMMENT '范围定义ID',
  PRIMARY KEY (`ID_`),
  KEY `ACT_IDX_IDENT_LNK_USER` (`USER_ID_`),
  KEY `ACT_IDX_IDENT_LNK_GROUP` (`GROUP_ID_`),
  KEY `ACT_IDX_IDENT_LNK_SCOPE` (`SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_IDENT_LNK_SUB_SCOPE` (`SUB_SCOPE_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_IDENT_LNK_SCOPE_DEF` (`SCOPE_DEFINITION_ID_`,`SCOPE_TYPE_`),
  KEY `ACT_IDX_ATHRZ_PROCEDEF` (`PROC_DEF_ID_`),
  KEY `ACT_FK_TSKASS_TASK` (`TASK_ID_`),
  KEY `ACT_FK_IDL_PROCINST` (`PROC_INST_ID_`),
  CONSTRAINT `ACT_FK_ATHRZ_PROCEDEF` FOREIGN KEY (`PROC_DEF_ID_`) REFERENCES `act_re_procdef` (`ID_`),
  CONSTRAINT `ACT_FK_IDL_PROCINST` FOREIGN KEY (`PROC_INST_ID_`) REFERENCES `act_ru_execution` (`ID_`),
  CONSTRAINT `ACT_FK_TSKASS_TASK` FOREIGN KEY (`TASK_ID_`) REFERENCES `act_ru_task` (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运作中人员表';


INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('batch.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('cfg.execution-related-entities-count', 'true', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('cfg.task-related-entities-count', 'true', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('common.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('entitylink.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('eventsubscription.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('identitylink.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('job.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('next.dbid', '1', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('schema.history', 'create(6.7.2.0)', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('task.schema.version', '6.7.2.0', 1);
INSERT INTO act_ge_property
(NAME_, VALUE_, REV_)
VALUES('variable.schema.version', '6.7.2.0', 1);
